### ISSUE TITLE
[Document] Description and flowchart contents do not match

### ISSUE THREAD

**Issue by sya-ri** [plasmoapp/plasmo-voice#109]
> Spigot and Fabric servers are compatible with both Fabric and Forge clients. Forge server is for Forge clients only.
>
> ...
>
> ![](https://imgur.com/dxgaWJ2.png)
>
> from [README.MD](https://github.com/plasmoapp/plasmo-voice/blob/9e8b1b6eb4b1fba1b7d5c03a43a822b09bd7a393/README.md#available-for-spigot-fabric-and-forge) 

The description says "Forge server is Forge client only", but the flowchart shows "Fabric client can use the voice chat in Forge server".

**Comment by Toldoven** [comment]
Fixed
