### ISSUE TITLE
This mod reconnecting problem

### ISSUE THREAD

**Issue by Tapo44ka** [plasmoapp/plasmo-voice#11]
Great plugin! I had a problem, namely, when I go to the server, I can speak for 10-30 seconds, then the mod turns off, namely, when I press V, it writes to me in the interface: Plasmo Voice is not installed on this server. What is causing this? (The port is open, with / vrc again, it works for 10-30 seconds, and turns off, I did everything according to the FAQ.

**Comment by KPidS** [comment]
Try to enter the IP address of your server in the config and check if this helps. 

```yml
udp:
# Enter the IP address of your server here 
  ip: 0.0.0.0
  port: 60606
```

If you already did so, try the opposite and just leave it as `0.0.0.0`.

And check the console and make sure there is no such message. If you see this message, check if the ports are open. Be aware that this is a UDP port. Ask your hosting provider if they have UDP ports open. 

![image](https://user-images.githubusercontent.com/27863947/114421229-c3bd0100-9bbd-11eb-96ab-917677513095.png)

**Comment by Tapo44ka** [comment]
Thanks!

**Comment by Tapo44ka** [comment]
Cough, cough, sorry, did you mean these by UDP ports?
![Screenshot_1](https://user-images.githubusercontent.com/69669408/114565395-e44a9100-9c79-11eb-9cb0-2e9c753cba56.png)

**Comment by Tapo44ka** [comment]
Log erro:
[11:10:51 WARN]: java.net.BindException: Cannot assign requested address (Bind failed)
[11:10:51 WARN]: at java.net.PlainDatagramSocketImpl.bind0(Native Method)
[11:10:51 WARN]: at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
[11:10:51 WARN]: at java.net.DatagramSocket.bind(DatagramSocket.java:392)
[11:10:51 WARN]: at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
[11:10:51 WARN]: at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:78)

**Comment by Tapo44ka** [comment]
Khe, I apologize, it turns out that the plugin does not work if you log in with the BungeeCord proxy.
