### ISSUE TITLE
Game crashes when opening the settings on a device with no inputs

### ISSUE THREAD

**Issue by mja00** [plasmoapp/plasmo-voice#112]
Currently if you try to open the settings menu on a device with no microphones, or inputs in general, it tries to get index 0 in a list of 0 elements and crashes the game. 

Here's the crash report generated: [https://paste.gg/p/mja00/56679d7e5ea949e6a670d270b24ca151](https://paste.gg/p/mja00/56679d7e5ea949e6a670d270b24ca151)

**Comment by Toldoven** [comment]
Fixed in 1.2.6: https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.6-client
