### ISSUE TITLE
When connect to singleplayer world twice, Minecraft will crash

### ISSUE THREAD

**Issue by pozitp** [plasmoapp/plasmo-voice#115]
Demonstration of the bug: https://youtu.be/amfanH4BULM
Crash report (logs): https://bytebin.lucko.me/9sfsqxd0Lk
Version of Plasmo Voice: 1.2.6
Everything works fine in multiplayer. There are no crashes (but the server with Plasmo Voice)

**Comment by Toldoven** [comment]
Fixed in 1.2.7 https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.7-client
