### ISSUE TITLE
Mute toggle while in Creative Inventory

### ISSUE THREAD

**Issue by Daniel-Haug** [plasmoapp/plasmo-voice#116]
This is not a big issue, but something that could be improoved.

So when you open the inventory, the mute button still toggles (m as default).
That becomes a issue in the creative mode inventory, when you use the search bar to search for a item and toggle mute by accident while typing. It would be convenient if the button doesnt toggle mute while in the inventory.
Of course you could set the mute button to a key that doesn't get used while searching, but its more convenient to use m.

Anyways, this mod/plugin is really well made 👍

**Comment by CalXee** [comment]
Perhaps bind the mute key or any other key that toggles when in the creative search bar not to something you usually will type with by default as a temporary mitigation?
