### ISSUE TITLE
Mod literally doesn't exist

### ISSUE THREAD

**Issue by Coach-mdl** [plasmoapp/plasmo-voice#120]
The curseforge page no longer exists... [](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice-client)

**Comment by Toldoven** [comment]
The project got rejected on CurseForge, and we are waiting for a response from Curse support.  Right now you can use GitHub releases for download: https://github.com/plasmoapp/plasmo-voice/releases

**Comment by itasli** [comment]
you should consider using modrinth instead

**Comment by Toldoven** [comment]
Also available on modrinth now https://modrinth.com/mod/plasmo-voice

**Comment by leetfin** [comment]
Any updates on this?

**Comment by leetfin** [comment]
@KPidS Hello, have there been any updates from Curse support?

**Comment by Toldoven** [comment]
> @KPidS Hello, have there been any updates from Curse support?

We literally didn't get a single reply from them in 3 months now. I've also created a second ticket about a month ago.

Maybe I should join their Discord and try to contact someone directly, but to be honest, I just don't really care about Curse now anyway.

**Comment by leetfin** [comment]
That's awful, I'll try and poke them to look at this issue. Hopefully it can get resolved  - I'd really like to be able to use this in modpacks.

**Comment by emielderckx** [comment]
> That's awful, I'll try and poke them to look at this issue. Hopefully it can get resolved - I'd really like to be able to use this in modpacks.

Modrinth will really soon support modpacks :)

**Comment by ChiefArug** [comment]
Poke was received on the CF Dev Discord, however someone will need to provide more information about it, just "look at this project link" isn't enough.
Something like ticket numbers, or how you contacted them the first time.

**Comment by Toldoven** [comment]
> Poke was received on the CF Dev Discord, however someone will need to provide more information about it, just "look at this project link" isn't enough. Something like ticket numbers, or how you contacted them the first time.

The ticket number is #103304 on https://support.curseforge.com

**Comment by leetfin** [comment]
@KPidS I've been poking the ticket again, community mods say to "reply to their ticket addressing that response, then let me know and i will poke it again."

**Comment by Toldoven** [comment]
The mod is now again available at CurseForge: https://www.curseforge.com/minecraft/mc-mods/plasmo-voice

We finally got a reply after 5 months had passed. The project got immediately reapproved after that.
