### ISSUE TITLE
Вылетает При заходе в меню Настроек

### ISSUE THREAD

**Issue by PastMC** [plasmoapp/plasmo-voice#125]
Нажимаю V и вылет лог ниже играю на телефоне через pojavlauncher

[lastet.log](https://www.mediafire.com/file/aq3bjjtx76micdc/latest.log/file)

**Comment by RandomTNT** [comment]
Пожалуйста пишите на английском.

**Comment by apehum** [comment]
pojavlauncher не поддерживается
