### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by emielderckx** [plasmoapp/plasmo-voice#13]
Hey here are some suggestions for your great pl/mod,

1. Make the server unmute command `/vunmute` it just makes more sense then `/unvmute`
2. `/vmutelist` a command to show everyone who is muted, and there time and reason
3. Make it possible to add a reason to vmutes: `/vmute [player] (time/perm) (reason)`
4. Upload your mod to modrinth because it is the future :)

**Comment by KPidS** [comment]
Good suggestions, thanks. Will be added in future updates.

**Comment by StarsDown64** [comment]
As a second to these features:
5. Notify all people with the voice.mute and voice.unmute permissions when someone gets muted/unmuted.

**Comment by Vekster007** [comment]
Hi! Most likely, this will seem like another stupid suggestion to you, but how do you like the idea of adding the ability to check the mandatory installation of the mod? In other words, a person will kick when connecting to the server, if he didn't install the mod. I have a server close to vanilla with a whitelist, but to log in, you need to write your nickname to the bot in Discord. Online + - 25 players. Checking for the mandatory installation of the mod has become a terrible headache for my admin.

**Comment by StarsDown64** [comment]
> Hi! Most likely, this will seem like another stupid suggestion to you, but how do you like the idea of adding the ability to check the mandatory installation of the mod? In other words, a person will kick when connecting to the server, if he didn't install the mod. I have a server close to vanilla with a whitelist, but to log in, you need to write your nickname to the bot in Discord. Online + - 25 players. Checking for the mandatory installation of the mod has become a terrible headache for my admin.

I know that forge clients send a list of installed mods on connect, and there should be plugins that allow you to check for mandatory mods.
Not sure about fabric though, I don't know if it sends a list of mods.
It would save the mod author a bit of time, but either solution could work

**Comment by emielderckx** [comment]
Would still like to modrinth download because curseforge is an absolute nightmare.
