### ISSUE TITLE
[Crash] crash on launch (Fabric)

### ISSUE THREAD

**Issue by MissGamerz** [plasmoapp/plasmo-voice#133]
Version: Fabric 1.17

**using:** [Fabric 1.17] Plasmo Voice 1.2.8.jar
**Log:** https://pastebin.com/V77HZ38b

this problem does not happen on plasmo voice 1.2.7

**Comment by Toldoven** [comment]
There was a small bug, we fixed it without changing the version. Re-download 1.2.8 and it should work

**Comment by MissGamerz** [comment]
okay thanks

**Comment by MissGamerz** [comment]
this isnt the case on modrinth but yes on github
