### ISSUE TITLE
[Feature Request] Please add to config ability to adjust MTU size

### ISSUE THREAD

**Issue by ilfarpro** [plasmoapp/plasmo-voice#139]
Please add to config ability to adjust MTU size, like in SimpleVoiceChat. This can help significantly improve connection stability and prevent packets loss. Simply you'll be able to use 48000 sample rate even with bad unstable connection, such as 4G ethernet etc.

**Comment by Toldoven** [comment]
Will be added in 2.0.0

**Comment by Toldoven** [comment]
Added in 2xx
