### ISSUE TITLE
[Bug] Impossible to play

### ISSUE THREAD

**Issue by x8c8r** [plasmoapp/plasmo-voice#142]
Fabric version: 1.17.1

When I installed latest versions of the mod 1.2.6-1.2.9 as soon as I launch the game and get into main menu, the menu starts to reload indefinitely. What I mean by that is that it shows the same screen as when you boot up the game or reload textures. And you can't stop it, or press any menu buttons.

**Comment by x8c8r** [comment]
Apart from Plasmo Voice I have these mods installed(Trying older versions of the mod rn)
![image](https://user-images.githubusercontent.com/41564630/146378840-d2df45f7-4293-484d-98f4-23622855a600.png)
P.S. v1.2.0 works

**Comment by apehum** [comment]
Update fabric api

**Comment by Toldoven** [comment]
If you update Fabric API this should fix the issue
