### ISSUE TITLE
No input sound

### ISSUE THREAD

**Issue by DimetryBadcoder** [plasmoapp/plasmo-voice#148]
There is no input sound until microphone is manually selected in the V menu (even if a proper one is already selected).

Mod list:
![Mod List](https://user-images.githubusercontent.com/93340769/147253249-3102477c-6a08-4ebf-a6aa-bf7de5f76bc2.png)

**Comment by Toldoven** [comment]
Are you perhaps testing it in the single-player?

**Comment by DimetryBadcoder** [comment]
> Are you perhaps testing it in the single-player?

Yes. And I tried on the fabric server with mod too.

**Comment by Toldoven** [comment]
This version should fix the issue: https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.10-alpha

I will close the issue, please let us know if you'll have this issue again. The version is released as alpha and available for 1.18 only, Forge & Fabric, with a port for the 1.17 and 1.16 coming when we will make sure that the version is stable.
