### ISSUE TITLE
Майнкрафт с фабрик не запускается с с модом

### ISSUE THREAD

**Issue by Fabuncgo** [plasmoapp/plasmo-voice#15]
Здравствуйте, я  установил ваш прекрасный мод на фабрик в папку модс с фабрик апи но при заходя в игру пишет ошибка 0

**Comment by Fabuncgo** [comment]
> Здравствуйте, я установил ваш прекрасный мод на фабрик в папку модс с фабрик апи но при заходя в игру пишет ошибка -1

**Comment by KPidS** [comment]
Скинь полные логи. .minecraft/logs/latest.log после запуска игры с крашем

**Comment by Fabuncgo** [comment]
[2021-04-20-6.log.gz](https://github.com/plasmoapp/plasmo-voice/files/6347405/2021-04-20-6.log.gz)

**Comment by Fabuncgo** [comment]
![изображение_2021-04-21_090856](https://user-images.githubusercontent.com/82883686/115482403-33e41a80-a281-11eb-9d66-619e4e7e4d7e.png)

**Comment by KPidS** [comment]
Попробуй удалить конфиги мода .minecraft/config/PlasmoVoice

**Comment by Fabuncgo** [comment]
нету такого файла

**Comment by KPidS** [comment]
Это не файл, а папка

> нету такого файла

**Comment by Fabuncgo** [comment]
![2021-04-21 (2)_LI](https://user-images.githubusercontent.com/82883686/115537201-2b193600-a2cd-11eb-8bb0-4a5cadd5d9b4.jpg)

**Comment by KPidS** [comment]
Ты уверен, что ты скинул нужные логи, которые были после краша? Запусти игру, чтобы она крашнулась, и потом скинь latest.log

**Comment by Fabuncgo** [comment]
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6352756/latest.log)

**Comment by KPidS** [comment]
У тебя стоит Optifabric? И вообще, скинь полностью весь список модов, и попробуй запустить игру только с Plasmo Voice.

**Comment by Fabuncgo** [comment]
Запустил без модов, все также а моды: оптифабрик, оптифайн, риплей мод, чат хед

**Comment by KPidS** [comment]
> Запустил без модов, все также а моды: оптифабрик, оптифайн, риплей мод, чат хед

Без модов это имеется ввиду, что ты запустил игру только с Plasmo Voice? Если да, то попробуй сделать наоборот и запустить игру со всеми модами кроме Plasmo Voice.

**Comment by Fabuncgo** [comment]
да, я запустил только Plasmo Voice ивсе моды без Plasmo Voice работают

**Comment by KPidS** [comment]
Какая версия Java? Нажми `Win+R`, в появившемся окне напиши `cmd`. Откроется командная строка и там нужно написать `java -version`. Скинь скриншот того, что получится.

**Comment by Fabuncgo** [comment]
![2021-04-22 (2)](https://user-images.githubusercontent.com/82883686/115724463-8b82a300-a3b3-11eb-9c30-e5e44266e37e.png)

**Comment by howkawgew** [comment]
@Fabuncgo на твоем первом скрине есть 'Посмотреть отчет об ошибке', можешь нажать и скинуть?

**Comment by Fabuncgo** [comment]
[crash-2021-04-22_21.54.36-client.txt](https://github.com/plasmoapp/plasmo-voice/files/6358808/crash-2021-04-22_21.54.36-client.txt)

**Comment by howkawgew** [comment]
Тем более, у тебя не самая новая версия Plasmo Voice(последняя 1.0.4, у тебя 1.0.3), скачай последнюю с [CurseForge](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice-client) и попробуй еще раз

**Comment by Fabuncgo** [comment]
> Тем более, у тебя не самая новая версия Plasmo Voice(последняя 1.0.4, у тебя 1.0.3), скачай последнюю с [CurseForge](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice-client) и попробуй еще раз

скачал, тоже самое

**Comment by howkawgew** [comment]
С какого юзера ты сидишь? У тебя есть админские права?

**Comment by Fabuncgo** [comment]
> С какого юзера ты сидишь? У тебя есть админские права?

а теперь тоже самое но по Русский

**Comment by howkawgew** [comment]
Ладно, давай так:
win+R -> cmd -> введи: "net session >nul 2>&1" и пришли скрин

**Comment by howkawgew** [comment]
> а теперь тоже самое но по Русский

Ты запускаешь майнкрафт с правами администратора или нет?

**Comment by Fabuncgo** [comment]
> > а теперь тоже самое но по Русский
> 
> Ты запускаешь лаунчер с правами администратора или нет?

Серьезно? Спасибо это действительно решило мою проблему

**Comment by howkawgew** [comment]
Если что, у тебя была проблема с тем что Java не могла создать файл в папке TEMP т.к. не было прав.
