### ISSUE TITLE
[Bug] Sometimes sounds quiet

### ISSUE THREAD

**Issue by sya-ri** [plasmoapp/plasmo-voice#156]
Since 1.2.8, occurs immediately after joining the server or suddenly. There are no logs such as error messages. Voice that sounds quiet may change to sound louder as usual. At that time, maybe there is "Close Opus Decoder" in log. However, if there is a log, it will not always recover.

**Comment by Toldoven** [comment]
Test this version, should no longer have this issue https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.10-client-test

**Comment by sya-ri** [comment]
Thank you. But my server has no Fabric users. Could you upload a jar for Forge 1.17.1 to try the version?

**Comment by Toldoven** [comment]
1.2.10 is released now for 1.17.1 and 1.16.4, the issue should be fixed. 

https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.10
