### ISSUE TITLE
Plasmo keep logging out from server

### ISSUE THREAD

**Issue by Pineappleguy03** [plasmoapp/plasmo-voice#157]
I have a friend Who can't seem to join. But when I read the logs. It disconnects him then minecraft tries to reconnect. Giving him an endless loop.
[debug.log](https://github.com/plasmoapp/plasmo-voice/files/7836055/debug.log)
[latest (1).log](https://github.com/plasmoapp/plasmo-voice/files/7836056/latest.1.log)

**Comment by Toldoven** [comment]
Is this issue still relevant? We can't figure out what the problem is just from the logs, and it needs further testing.
