### ISSUE TITLE
Spams console

### ISSUE THREAD

**Issue by Silent-Program** [plasmoapp/plasmo-voice#158]
Hello, the server plugin spams the console with this...

`14.01 18:56:07 [Server]  at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:100)
14.01 18:56:12 [Server]  java.lang.IllegalArgumentException: Invalid UUID string: 
14.01 18:56:12 [Server]  at java.base/java.util.UUID.fromString1(UUID.java:280)
14.01 18:56:12 [Server]  at java.base/java.util.UUID.fromString(UUID.java:258)
14.01 18:56:12 [Server]  at su.plo.voice.common.packets.udp.VoiceServerPacket.read(VoiceServerPacket.java:43)
14.01 18:56:12 [Server]  at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:98)
14.01 18:56:12 [Server]  at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:100)
14.01 18:56:17 [Server]  java.lang.IllegalArgumentException: Invalid UUID string: 
14.01 18:56:17 [Server]  at java.base/java.util.UUID.fromString1(UUID.java:280)
14.01 18:56:17 [Server]  at java.base/java.util.UUID.fromString(UUID.java:258)
14.01 18:56:17 [Server]  at su.plo.voice.common.packets.udp.VoiceServerPacket.read(VoiceServerPacket.java:43)
14.01 18:56:17 [Server]  at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:98)
14.01 18:56:17 [Server]  at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:100)`
Proof of it spamming, it shows twice there.

Plugin list seen here
![image](https://user-images.githubusercontent.com/72319773/149570137-756f3e58-2295-42c8-8b4c-ea541df8e2cc.png)

**Comment by Silent-Program** [comment]
I am using protocollib

**Comment by Toldoven** [comment]
Fixed in 1.0.9

https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.9-spigot
