### ISSUE TITLE
[Feature Request] Port multiplexing

### ISSUE THREAD

**Issue by Ghost-chu** [plasmoapp/plasmo-voice#159]
Our networks have ton of subservers, but the question is we only have limited ports availiable.

PlasmoVoice every instance will took one port from poor ports pool, which really painful.

Our CLB and DDoS protections services really expensive and billing by each-port.

So I want open ticket for feature port multiplexing -- which PlasmoVoice can open a "bridge" server (like BungeeCord proxy) and forwarding user connection/traffic from bridge to backend Spigot server.

Example:

User <-> Bridge (one port for public) <-> many internal access only PlasmoVoice server that installed on Spigot server.
<img width="542" alt="screenshot 2022-01-16 145902" src="https://user-images.githubusercontent.com/30802565/149650570-de4c64fd-0e49-4159-b0f7-98ae7d722b34.png">

**Comment by Toldoven** [comment]
Added in 2xx. Docs will be out soon

**Comment by Ghost-chu** [comment]
Glad to hear it has been added into Plasmo! 👍



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 22:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [plasmoapp/plasmo-voice] [Feature Request] Port multiplexing(Issue #159)




 
Closed #159 as completed.
