### ISSUE TITLE
Не видит плагин у стороннего игрока.

### ISSUE THREAD

**Issue by HyperBOXed** [plasmoapp/plasmo-voice#16]
На сервере 1.16.5 с ядром Paper установлен плагин plasmovoice-server-1.0.2.
У меня установлен мод Forge plasmovoice-forge-1.0.3.
При старте сервера плагин пишет всё то, что и должно быть при успешной загрузке. На сервере у меня весь функционал PlasmoVoice работает.
Но проблема в том, что у другого игрока, с тем же самым установленным модом и версией 1.16.5 при заходе на сервер, пишет, что плагин PlasmoVoice не найден на сервере. Что это может быть и как это можно решить, подскажите, пожалуйста.

**Comment by KPidS** [comment]
Ты запускаешь сервер на своём компьютере или хостинге? Если на хостинге, то на каком?

**Comment by KPidS** [comment]
Посмотри пожалуйста статью по установке плагина на сервер. Проверь чтобы порт был открыт, и чтобы он не был занят чем-то другим. Попробуй установить такой же порт, какой у сервера. Попробуй поставить IP в строчке с IP в конфиге. Если уже ставил, то убери.

Это должно фиксить проблемы с плагином в 99% случаях, и если это не поможет, то есть проблемы с твоей стороны. Можешь попросить помощь у своего хостинг провайдера.

**Comment by HyperBOXed** [comment]
Сервер стоит на хостинге Aternos. В плагинах PlasmoVoice отображается, а мод пишет, что плагина нет.
![image](https://user-images.githubusercontent.com/73667233/115761691-ab19cb80-a3b3-11eb-84b9-245ec0aa3993.png)
![image](https://user-images.githubusercontent.com/73667233/115761703-b1a84300-a3b3-11eb-969f-d13853e17cd6.png)

**Comment by KPidS** [comment]
Там нужно установить порт такой же как у сервера. Смотри этот гайд: https://support.aternos.org/hc/en-us/articles/360019336497-Installing-Voice-Chat-Mods
