### ISSUE TITLE
how can I compile it by its source code

### ISSUE THREAD

**Issue by MoonCakeMC** [plasmoapp/plasmo-voice#160]
I need some function that the original edition haven't, but after I modify it, I can't compile it to a jar file to be my plugin

**Comment by Toldoven** [comment]
You can request the features you need or create a pull request. 

We won't explain how to compile the mod, but you can figure it out yourself.

**Comment by MoonCakeMC** [comment]
I hope the whole server can hear my voice. In my practice, I found that even if I set the maximum distance to 32767, other players can't hear my voice outside the 2 chunks.

I used a translator for this paragraph, because my mother tongue is not English, there may be grammatical errors, please forgive me

**Comment by Toldoven** [comment]
> I hope the whole server can hear my voice. In my practice, I found that even if I set the maximum distance to 32767, other players can't hear my voice outside the 2 chunks.
> 
> I used a translator for this paragraph because my mother tongue is not English, there may be grammatical errors, please forgive me

Players won't hear you if you are not in their render distance. The voice distance is capped by the server/client render distance. With the current protocol, it's hard to add a feature to bypass that reliably, but it will be easy when version 2.0.0 comes out.
