### ISSUE TITLE
[Crash] Won't Launch with Plasmo Voice Installed

### ISSUE THREAD

**Issue by greensad** [plasmoapp/plasmo-voice#162]
TBH I'm not sure where to start with this stacktrace, sorry! Hope my log is of some use: https://paste.ee/p/59XqE

**Comment by thehaffk** [comment]
![IMG_20220122_105934_567.jpg](https://user-images.githubusercontent.com/73640655/150630222-9d6379ac-b77a-4dad-b331-1e6079d32cab.jpg) Pepega

**Comment by greensad** [comment]
LOL this is the second time this week, my b, and sorry!!
