### ISSUE TITLE
[Feature Request] Voice Channel Support

### ISSUE THREAD

**Issue by Xmonpl** [plasmoapp/plasmo-voice#165]
Adding possibility to api to set which channel a player should talk on. It would be nice if it looked like this:

```java
    /**
     * Set the channel for the player
     *
     * @param player       Player UUID
     * @param channel     ChannelId (int) if channel null create voice channel
     *
     */
    void setChannel(UUID player, int channel);
```

**Comment by ghost** [comment]
also, it'll be great with API supports for other plugins. Like Team minigame voice channel.

**Comment by Toldoven** [comment]
The new API is much more flexible than the supposed change, so there is no need to implement this. 

As an example, check out the groups add-on: https://github.com/plasmoapp/pv-addon-groups
