### ISSUE TITLE
как бы работает, а как бы нет

### ISSUE THREAD

**Issue by kikita0** [plasmoapp/plasmo-voice#17]
спигот. вроде плагин работает, есть его команды, но при нажатии на v или alt ничего не происходит, и в списке пользующихся меня нет

**Comment by KPidS** [comment]
> спигот. вроде плагин работает, есть его команды, но при нажатии на v или alt ничего не происходит, и в списке пользующихся меня нет

Посмотри пожалуйста статью по установке плагина на сервер. Проверь чтобы порт был открыт, и чтобы он не был занят чем-то другим. Попробуй установить такой же порт, какой у сервера. Попробуй поставить IP в строчке с IP в конфиге. Если уже ставил, то убери. 

Это должно фиксить проблемы с плагином в 99% случаях, и если это не поможет, то есть проблемы с твоей стороны. Можешь попросить помощь у своего хостинг провайдера.
