### ISSUE TITLE
Crash when changing microphone device

### ISSUE THREAD

**Issue by ShadowFlare** [plasmoapp/plasmo-voice#170]
Whenever changing the microphone selected, whether clicking from the list or clicking reset, the game is crashing for me. Output device selection still works fine, however. This is on 1.18.1-1.2.10-alpha, either Fabric or Forge it does the same crash.

**Comment by emielderckx** [comment]
Here is the client output of this crash: https://mclo.gs/UYGGEGS

**Comment by ShadowFlare** [comment]
By the way, it does seem to save the change at least, so that once the game is restarted you can see the device selected that you tried to select.

**Comment by ShadowFlare** [comment]
Tried the latest version and seems good, no crash 👍
