### ISSUE TITLE
bungeecord configure not working

### ISSUE THREAD

**Issue by Kanorto** [plasmoapp/plasmo-voice#172]
I did everything in accordance with the guide, nginx works, but now the server does not start because nginx is already running to listen on this port. 
`25565: bind: address already in use`

**Comment by Kanorto** [comment]
I did everything in accordance with the guide, nginx works, but now the server does not start because nginx is already running to listen on this port

**Comment by Kanorto** [comment]
nginx.conf
`stream {
  server {
    listen     25565 udp; 
    proxy_pass IP:PORT; 
  }
}`
plasmovoiice config
`udp:
  ip: 0.0.0.0
  port: PORT Spigot
  proxy_ip: IP PROXY
  proxy_port: 25565 `

**Comment by Toldoven** [comment]
This has nothing to do with bungee: https://imgur.com/sMFu07R

Bungee is the proxy you use for the Minecraft server. Nginx is the proxy you use for the voice chat. Those are 2 separate proxies, and they need to run on different ports.

**Comment by Toldoven** [comment]
Just please read the guide again, or join our Discord and ask for help in the #need-help channel, if you still don't understand how to set it up.
