### ISSUE TITLE
Inconsistent Capitalization Styling

### ISSUE THREAD

**Issue by yurisuika** [plasmoapp/plasmo-voice#179]
The capitalization of the translations, at least for EN_US, is inconsistent with vanilla styling.

For example, instead of `Push-to-talk button` use `Push-to-Talk Button` or perhaps `Push-To-Talk Button`, or instead of `Voice settings` use `Voice Settings`.

This would improve the appearance of the mod and give it a more professional, polished edge!

**Comment by Toldoven** [comment]
Can you perhaps make a PR fixing this issue? Maybe I'm dumb, but I don't really get what you mean by "vanilla styling".

**Comment by yurisuika** [comment]
Sure thing! It is the least I can do for such a great mod. If only I had people I could use it with haha. :(

Anyways, I had already made a resource pack to alter the lang file for it and some other mods. I am only fluent in English though so I am probably not the one to attempt the revision for other languages.

You can see here vanilla text capitalizes every word, even prepositions, in many menu areas. As it is in PV only the first words are capitalized.

![image](https://user-images.githubusercontent.com/7410303/156903446-3ac8b110-fe3f-4676-8433-9d106d03309b.png)
