### ISSUE TITLE
mistake in word "bug"

### ISSUE THREAD

**Issue by PerchunPak** [plasmoapp/plasmo-voice#18]
![image](https://user-images.githubusercontent.com/68118654/115676080-e7b7d980-a357-11eb-8890-9add3c0e0c5a.png)
https://github.com/plasmoapp/plasmo-voice/wiki/Troubleshooting-&-FAQ#ive-found-a-but--i-have-a-suggestion--i-need-help

**Comment by KPidS** [comment]
Fixed
