### ISSUE TITLE
Bungee and Velocity support

### ISSUE THREAD

**Issue by cardanawandra** [plasmoapp/plasmo-voice#183]
big need

**Comment by Timtaran** [comment]
+

**Comment by emielderckx** [comment]
plasmovoice works fine with bungee and velocity

**Comment by Toldoven** [comment]
Like @emielderckx already said, it works with Bungee and Velocity. You just install it on every backend server as usual. Or if you need to also proxy voice traffic, you can set up a separate proxy for that. You can read the wiki if you need more info on that. Also, an improved version of the installation guide is coming soon, which will cover that in more detail. 

 It's not complete support. For example, you can't mute people on multiple servers at the same time. But for now, it's good enough.
 
 Bungee plugin will probably be available with version 2.0.0.
