### ISSUE TITLE
[Crash] [FTB] [1.16.5] Crashes with any FTB mod when opening menu

### ISSUE THREAD

**Issue by Merith-TK** [plasmoapp/plasmo-voice#185]
https://mclo.gs/GeIGqNt

open world, press keybind to open the Plasmo Menu, happens in multiplayer and singleplayer, 

this happens whenever you open the voice menu, no matter the keybind

Mods in use, default configs
![image](https://user-images.githubusercontent.com/10422110/156621744-69e9f6a6-376d-4fea-bf3b-090e60e9a3e6.png)

**Comment by Merith-TK** [comment]
those changes were done on 1.18? need this on 1.16 as plasmo is so much more performant than simple voice chat

**Comment by drakosoldier298** [comment]
Yeah i also need thsi fix on 1.16.5 my server cant update yet.

**Comment by Toldoven** [comment]
The fix is not out yet, but when it releases it will be also available for 1.16.5

**Comment by apehum** [comment]
Fixed in 1.2.11:
https://modrinth.com/mod/plasmo-voice/versions
[1.16 forge] https://modrinth.com/mod/plasmo-voice/version/forge-1.16-1.2.11
