### ISSUE TITLE
Crash on bootup

### ISSUE THREAD

**Issue by YnwLNE** [plasmoapp/plasmo-voice#190]
Was installing a few mods when the client crashed, isolated down to this mod but due to the crash it doesn't make a log, here's the latest log. 

https://pastebin.com/4c1Av5s1

**Comment by Toldoven** [comment]
1.2.11 only runs on Minecraft 1.18.2 and doesn't work on 1.18.1. The last version that works on 1.18.1 is 1.2.10: https://modrinth.com/mod/plasmo-voice/version/fabric-1.18-1.2.10
