### ISSUE TITLE
Patcher GUI

### ISSUE THREAD

**Issue by uhhams** [plasmoapp/plasmo-voice#193]
My microphone isnt being detected and only displays CoreAudioDefualt in the menu. I saw the closed issue but cant figure out how to manually patch the issue since it doesnt give me it automatically. (im on macos)

**Comment by Toldoven** [comment]
There is a standalone version: https://github.com/henkelmax/simple-voice-chat/tree/1.18.1/macos#standalone-version

**Comment by uhhams** [comment]
so how would I install that for plasmo?
