### ISSUE TITLE
There is a standalone version: https://github.com/henkelmax/simple-voice-chat/tree/1.18.1/macos#standalone-version

### ISSUE THREAD

**Issue by uhhams** [plasmoapp/plasmo-voice#197]
There is a standalone version: https://github.com/henkelmax/simple-voice-chat/tree/1.18.1/macos#standalone-version

_Originally posted by @KPidS in https://github.com/plasmoapp/plasmo-voice/issues/193#issuecomment-1100646254_

how would I install this for plasmo? this is for simple voice chat

**Comment by Toldoven** [comment]
You don't need to install it, you just run it
