### ISSUE TITLE
Mod Not Available

### ISSUE THREAD

**Issue by TexanszYT** [plasmoapp/plasmo-voice#2]
The mod on Forge is unavailable. Is there an alternate link?

**Comment by lit7355** [comment]
No, this mod is created on Fabric. There isnt any Forge versions.

**Comment by KPidS** [comment]
CurseForge page is not approved yet. Use [GitHub releases](https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.0) to download the client.
