### ISSUE TITLE
Так, я сильно озадачен.

### ISSUE THREAD

**Issue by ReddyCorr** [plasmoapp/plasmo-voice#20]
Рассказываю что происходит:

Я устанавливаю Plasmo на сервер, всё вроде работает, у всех игроков всё хорошо. Но почему-то когда они пытаются настроить мод - у них сначала крашится Майнкрафт, а потом, когда всё становится нормальным и не крашится - через время говорит, что на сервере нет плагина для Plasmo. Вроде пытался несколько раз менять IP, порт - ничего не поменялось. 
Что это за чертовщина? Я очень хочу играть с этим плагином/модом, как и все остальные на сервере, а вот тут такой казус появился.

**Comment by Omni6x** [comment]
Та же самая проблемма, люди заходят на сервер а им пишет что мод не установлен, хотя мод установлен и папка мода появилась.

**Comment by howkawgew** [comment]
Посмотрите пожалуйста статью по установке плагина на сервер. Проверьте чтобы порт был открыт, и чтобы он не был занят чем-то другим. Попробуйте установить такой же порт, какой у сервера. Попробуйте поставить IP в строчке с IP в конфиге. Если уже ставили, то уберите.

Это должно фиксить проблемы с плагином в 99% случаях, и если это не поможет, то есть проблемы с вашей стороны. Можете попросить помощь у своего хостинг провайдера.

**Comment by ReddyCorr** [comment]
Я всё делал, именно всё, что нужно.
Мой сервер стоит на Атерносе, и я ввёл именно порт и именно айпи - всё равно ничего не поменялось.
Как мне быть?

**Comment by howkawgew** [comment]
Атернос не является хорошим хостингом для Plasmo Voice - у тебя нет возможности контролировать порты. Даже если порты открыты то не факт что атернос позволит моду присылать пакеты на сервер корректно. 

Проблема в хостинге. Могу предложить всего два решения:

- Написать в тех. поддержку Aternos и разобраться с проблемой через них.
 
 - Сменить хостинг.

**Comment by howkawgew** [comment]
@Omni6x **каким хостинг-провайдером вы пользуетесь? Вы пробовали менять конфиг? Вы уверены что у вас открыт указанный порт?**

**Comment by ReddyCorr** [comment]
> Aternos не является хорошим хостингом для Plasmo Voice - у вас нет возможности контролировать порты. Даже если порты открыты, то не факт что Aternos позволит моду присылать пакеты на сервер корректно.
> 
> **Проблема, вероятнее всего, в хостинге.** Могу предложить всего два решения:
> 
> * Написать в тех. поддержку Aternos и разобраться с проблемой через них.
> * Сменить хостинг.

Хостинг, к сожалению, я не смогу изменить по бюджетным обстоятельствам...
Так что я попробую поговорить с тех. поддержкой.

**Comment by Omni6x** [comment]
> @Omni6x **каким хостинг-провайдером вы пользуетесь? Вы пробовали менять конфиг? Вы уверены что у вас открыт указанный порт?**
Использую Hosting-Minecraft.ru, вроде как нормальный хостинг, на сервере порт открыт, у меня наверное нет но на другом сервере с этим плагином он работает.

**Comment by howkawgew** [comment]
> Хостинг, к сожалению, я не смогу изменить по бюджетным обстоятельствам...
Существует еще много бесплатных хостингов. Google в помощь.

> Так что я попробую поговорить с тех. поддержкой.
Если во время диалога с поддержкой появятся вопросы - можете задавать их в этот issue, удачи.

**Comment by Omni6x** [comment]
Пошаманил с портом, и айпишником и все заработало, были указаны немного не стандартные показатели
Проблемма была у меня все настроил, спасибо за ответы

**Comment by KPidS** [comment]
Я сегодня устанавливал мод на Aternos и там всё работает просто замечательно. Нужно просто поставить порт в плагине Plasmo Voice на тот же порт, на котором работает сам сервер. Смотрите этот гайд: https://support.aternos.org/hc/en-us/articles/360019336497-Installing-Voice-Chat-Mods

Он написан для других модов на голосовой чат, но с нашим всё работает аналогично.

**Comment by KPidS** [comment]
Насчет крашей, установите последнюю версии плагина и мода. Мы пофиксили все известные краши на данный момент. Если они всё ещё будут, то открывайте новые Issues с описанием конкретных крашей, желательно прикрепляйте логи.
