### ISSUE TITLE
помогите 

### ISSUE THREAD

**Issue by lemonfroggy4** [plasmoapp/plasmo-voice#205]
у меня бесконечное подключение к UPD серверу на спзомбу мод plasmo voise

**Comment by thehaffk** [comment]
невероятно

**Comment by thehaffk** [comment]
помогу когда правильно назовешь протокол, не будешь искажать название сервера и перестанешь открывать issue без какой-либо информации

**Comment by lemonfroggy4** [comment]
Извини, я только вчера зарегался и не знаю что такое протокол. Сервер так и называется спz или спzombu. И информацию дать не могу, так как единственное что я могу дать из инфы это то что при открытие настроек голосового чата у меня появляется табличка с бесконечным подключением к UPD серверу

**Comment by Euro-pol** [comment]
UDP
