### ISSUE TITLE
Forge any version no mic input

### ISSUE THREAD

**Issue by TheHackerYTB** [plasmoapp/plasmo-voice#207]
So i wanted this mod but when i tested voice no input i go to see if the game uses my microphone and nothing

Windows 10 Latest Version

**Comment by TheHackerYTB** [comment]
So it works its using my mic put no input i speak on all microfones nothing from mic testing

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
