### ISSUE TITLE
Assigning buffer data: Invalid parameter parameter value

### ISSUE THREAD

**Issue by Binero** [plasmoapp/plasmo-voice#208]
Sometimes I get this error on the client and then I stop hearing voice sounds. Others can still hear me though.

[00:28:57] [Thread-836/ERROR]: Assigning buffer data: Invalid parameter parameter value.

I have to do /vrc to fix it, it happens every 5 minutes or so

**Comment by apehum** [comment]
Fixed in 1.2.15
Fabric: https://modrinth.com/mod/plasmo-voice/version/fabric-1.19-1.2.15
Forge: https://modrinth.com/mod/plasmo-voice/version/forge-1.19-1.2.15
