### ISSUE TITLE
Can't hear others audio until server relog

### ISSUE THREAD

**Issue by xameryn** [plasmoapp/plasmo-voice#210]
This came up a few times in about an hour of testing. Everything works fine until randomly you can't hear the other users voice, the speaking icon appears above their head but you can't hear their voice. After a relog it's resolved until it comes up again. This happened both ways.

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
