### ISSUE TITLE
PlayerSpeakEvent is never called.

### ISSUE THREAD

**Issue by slavita256bit** [plasmoapp/plasmo-voice#211]
Hello everyone! Im trying to create my plugin with plasmovoice communication. 
I need to use PlayerSpeakEvent but it is never called.

![image](https://user-images.githubusercontent.com/52290641/173878277-c257b0a9-e0f3-4d25-a60a-b23126df0466.png)

I think it should be placed here.

![code](https://user-images.githubusercontent.com/52290641/173880759-b2b47af1-45c7-4d82-98f8-1cc4daa61aab.png)

Thanks for answer

Slavita

**Comment by Roman-Andr** [comment]
Yeah, it should be fixed.

**Comment by apehum** [comment]
Fixed in 1.0.11:
https://www.spigotmc.org/resources/plasmo-voice-server.91064/download?version=463250
