### ISSUE TITLE
don't work on bungeecord

### ISSUE THREAD

**Issue by bUmmy1337** [plasmoapp/plasmo-voice#214]
I have installed plasmovoice on every server
but when i join it doesn't work
it says: Connecting to UDP server...
i have 2 ports on server and second port i wrote in config
query=false
![изображение](https://user-images.githubusercontent.com/92600850/174593224-0f3d6252-dfb6-4ece-a907-574f2626f55b.png)

**Comment by StKillReal** [comment]
How did u fix it
