### ISSUE TITLE
микрофон не работает в ОС Linux (Arch)

### ISSUE THREAD

**Issue by SkyWatcher2019** [plasmoapp/plasmo-voice#215]
Микрофон работает на винде, работает в дс, но не работает на линусе

**Comment by gmankab** [comment]
does micro works in disciord on linux?

**Comment by SkyWatcher2019** [comment]
works in discord, browsers, obs, audacity

**Comment by GroobleDierne** [comment]
Same issue on Pop!_OS (Ubuntu derivative), I can select the mix but no sound is detected.

**Comment by PRIMUS8** [comment]
О у меня возможно та же проблема. Вчера поставил Fedora Linux, микрофон везде работает, кроме плазмавойса. Позавчера когда был виндоус всё везде работало.

**Comment by nikes** [comment]
Is problem here https://github.com/plasmoapp/plasmo-voice/blob/client-1.18-1.2.x/common/src/main/java/su/plo/voice/client/sound/Recorder.java
with problem from here https://stackoverflow.com/questions/17255344/capturing-audio-streams-in-java about how sample and detect data from linux data format too
https://www.codejava.net/coding/capture-and-record-sound-into-wav-file-with-java-sound-api#comment-17519
https://stackoverflow.com/questions/65660266/java-targetdataline-not-picking-up-any-audio

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
