### ISSUE TITLE
Не биндится PlasmoVoice на порт

### ISSUE THREAD

**Issue by nukerash** [plasmoapp/plasmo-voice#217]
Здравствуйте! у меняя такая проблема, когда в первый раз устанавливаю плазму и через vreload меняю конфиг на айпи сервера и порт сервера, то все работает, но после перезагрузки сервера ему не удается забиндится на порт.
Сервер стоит на Pterodactyl возможно в нем проблема, помогите пожалуйста,
P.s Может он не убивает процесс сервера плазмы и по этому не работает? (догадка) если да то как это исправить?
```
[05:23:06 INFO]: [PlasmoVoice] Enabling PlasmoVoice v1.0.10
[05:23:06 WARN]: java.net.BindException: Cannot assign requested address
[05:23:06 WARN]:        at java.base/sun.nio.ch.Net.bind0(Native Method)
[05:23:06 WARN]:        at java.base/sun.nio.ch.Net.bind(Net.java:555)
[05:23:06 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194)
[05:23:06 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164)
[05:23:06 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:107)
[05:23:06 WARN]:        at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1426)
[05:23:06 WARN]:        at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:330)
[05:23:06 WARN]:        at plasmovoice-server-1.0.10.jar//su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:86)
[05:23:06 INFO]: [PlaceholderAPI] Successfully registered expansion: plasmovoice [1.0.0]
[05:23:06 INFO]: [PlasmoVoice] Failed to bind socket. Check if port 25560 UDP is open
```

**Comment by ghost** [comment]
Привет! Походу я знаю для тебя решение. Иди в конфиг и измени там айпи на 172.17.0.1 либо 172.18.0.1. Да ты верно сказал что это проблема в Pterodactyl. Просто измени айпи на который я тебе сказал. Я думаю это тебе поможет.

P.S. То что я тебе сказал ввыше - не правильно. В конфиге измени айпи на 0.0.0.0, открой порт в системе и у меня после этого заработало. А также присвой к серверу в Pterodactyl тот порт, который ты указал в плагине.

**Comment by nukerash** [comment]
> Привет! Походу я знаю для тебя решение. Иди в конфиг и измени там айпи на 172.17.0.1 либо 172.18.0.1. Да ты верно сказал что это проблема в Pterodactyl. Просто измени айпи на который я тебе сказал. Я думаю это тебе поможет.
> 
> P.S. То что я тебе сказал ввыше - не правильно. В конфиге измени айпи на 0.0.0.0, открой порт в системе и у меня после этого заработало. А также присвой к серверу в Pterodactyl тот порт, который ты указал в плагине.

Привет! сейчас вместо птеры я поставил просто на линукс с управлением через скрины, но проблема та же самая (у меня установлен тцп шилд) я хз че делать(

P.s я попробовал и на 0.0.0.0 поставить и на все другие но ничего не сработало(

**Comment by ghost** [comment]
> > Привет! Походу я знаю для тебя решение. Иди в конфиг и измени там айпи на 172.17.0.1 либо 172.18.0.1. Да ты верно сказал что это проблема в Pterodactyl. Просто измени айпи на который я тебе сказал. Я думаю это тебе поможет.
> > P.S. То что я тебе сказал ввыше - не правильно. В конфиге измени айпи на 0.0.0.0, открой порт в системе и у меня после этого заработало. А также присвой к серверу в Pterodactyl тот порт, который ты указал в плагине.
> 
> Привет! сейчас вместо птеры я поставил просто на линукс с управлением через скрины, но проблема та же самая (у меня установлен тцп шилд) я хз че делать(
> 
> P.s я попробовал и на 0.0.0.0 поставить и на все другие но ничего не сработало(

А ты открывал порт для UDP? Если да то попробуй ещё и для TCP.
Вот как я открывал:
- sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
- sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport ПОРТ -j ACCEPT
- sudo iptables -I OUTPUT -m state --state NEW -p udp --dport ПОРТ -j ACCEPT

**Comment by nukerash** [comment]
> > > Привет! Походу я знаю для тебя решение. Иди в конфиг и измени там айпи на 172.17.0.1 либо 172.18.0.1. Да ты верно сказал что это проблема в Pterodactyl. Просто измени айпи на который я тебе сказал. Я думаю это тебе поможет.
> > > P.S. То что я тебе сказал ввыше - не правильно. В конфиге измени айпи на 0.0.0.0, открой порт в системе и у меня после этого заработало. А также присвой к серверу в Pterodactyl тот порт, который ты указал в плагине.
> > 
> > 
> > Привет! сейчас вместо птеры я поставил просто на линукс с управлением через скрины, но проблема та же самая (у меня установлен тцп шилд) я хз че делать(
> > P.s я попробовал и на 0.0.0.0 поставить и на все другие но ничего не сработало(
> 
> А ты открывал порт для UDP? Если да то попробуй ещё и для TCP. Вот как я открывал:
> 
> * sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> * sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport ПОРТ -j ACCEPT
> * sudo iptables -I OUTPUT -m state --state NEW -p udp --dport ПОРТ -j ACCEPT

я вообще отключил фаерволл поэтому (наверное) не в этом дело, порты для майна открылись сами

**Comment by nukerash** [comment]
> > > Привет! Походу я знаю для тебя решение. Иди в конфиг и измени там айпи на 172.17.0.1 либо 172.18.0.1. Да ты верно сказал что это проблема в Pterodactyl. Просто измени айпи на который я тебе сказал. Я думаю это тебе поможет.
> > > P.S. То что я тебе сказал ввыше - не правильно. В конфиге измени айпи на 0.0.0.0, открой порт в системе и у меня после этого заработало. А также присвой к серверу в Pterodactyl тот порт, который ты указал в плагине.
> > 
> > 
> > Привет! сейчас вместо птеры я поставил просто на линукс с управлением через скрины, но проблема та же самая (у меня установлен тцп шилд) я хз че делать(
> > P.s я попробовал и на 0.0.0.0 поставить и на все другие но ничего не сработало(
> 
> А ты открывал порт для UDP? Если да то попробуй ещё и для TCP. Вот как я открывал:
> 
> * sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> * sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport ПОРТ -j ACCEPT
> * sudo iptables -I OUTPUT -m state --state NEW -p udp --dport ПОРТ -j ACCEPT

может созвонимся в дискорде? сможешь помочь?

**Comment by ghost** [comment]
> * sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> * sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport ПОРТ -j ACCEPT
> * sudo iptables -I OUTPUT -m state --state NEW -p udp --dport ПОРТ -j ACCEPT

Попробуй в конфиге изменить порт на тот который указан в сервер.пропертиес, попробуй изменить адрес например на 127.0.0.1 и попробуй ввести это в линукс:
- hostname -I | awk '{print $1}'
Оно выдаст локальный айпи и попробуй ввести этот айпи в конфиг.

**Comment by nukerash** [comment]
> > * sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> > * sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport ПОРТ -j ACCEPT
> > * sudo iptables -I OUTPUT -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> 
> Попробуй в конфиге изменить порт на тот который указан в сервер.пропертиес, попробуй изменить адрес например на 127.0.0.1 и попробуй ввести это в линукс:
> 
> * hostname -I | awk '{print $1}'
>   Оно выдаст локальный айпи и попробуй ввести этот айпи в конфиг.

Так у меня оно заработает а у игроков нет

**Comment by nukerash** [comment]
> > * sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> > * sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport ПОРТ -j ACCEPT
> > * sudo iptables -I OUTPUT -m state --state NEW -p udp --dport ПОРТ -j ACCEPT
> 
> Попробуй в конфиге изменить порт на тот который указан в сервер.пропертиес, попробуй изменить адрес например на 127.0.0.1 и попробуй ввести это в линукс:
> 
> * hostname -I | awk '{print $1}'
>   Оно выдаст локальный айпи и попробуй ввести этот айпи в конфиг.

я поставил войс, сначало все работало но после перезагрузки серва войс перестал работать и снова ошибка о том что не может забиндится

**Comment by nukerash** [comment]
на локал адресс биндится на изи, а когда пытаюсь сделать для всех а не только для себя то ошибку вкидывает, скорее всего потому что сервер стоит на 25568, можно как-то сделать войс на другой порт? если да то как или сделать отдельную проксю? у меня тцп шилд + велосити
