### ISSUE TITLE
[Question] Usage with Sound Physics Remastered and Audio Engine features

### ISSUE THREAD

**Issue by iblowmymind** [plasmoapp/plasmo-voice#218]
How does Sound Physics mods (e.g., Sound Physics Remastered) and features of the Audio Engine (HRTF, Directional Sources, Sound Occlusion) work when they're installed together?

For example, should I enable these features when Sound Physics Remastered is enabled? Should I keep them both enabled for them to work? Do they conflict / break or is it even necessary to enable these features in Plasmo Voice when Sound Physics Remastered is installed?

Thanks!

**Comment by Toldoven** [comment]
They should be compatible. You can't enable Sound Occlusion though, the option is blocked when Sound Physics is installed.
