### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ChrisS-code** [plasmoapp/plasmo-voice#22]
Hey, i have a bit of a problem.
My friends and i have a aternos server, and it works really great.
Now we wanted to experiment with proximity chat, and this is the best plugin we could find for spigot.
My friend uses tlaucher, and i use official minecraft, and it worked just fine for me.
But my friend put the fabric mod in his mod folder, and he cant press v or talk with me. I also see the icon for no mod above my friends name. Did we do something wrong?

Thanks for the help.

**Comment by KPidS** [comment]
![image](https://user-images.githubusercontent.com/27863947/115894249-b9bebc00-a461-11eb-93bd-958b96209d58.png)

**Comment by KPidS** [comment]
If you installing this plugin on Aternos, then check out this guide: https://support.aternos.org/hc/en-us/articles/360019336497-Installing-Voice-Chat-Mods

It was made for a different mod, but it works the same for Plasmo Voice. Basically, you need to set the voice chat port to the same port your server uses.

**Comment by KPidS** [comment]
He didn't install the mod properly. TLaucnher doesn't have Fabric option by default, you need to download it from Fabric website and install it. It may be the case that he uses Forge instead, and installed the wrong version of the mod for Fabric. If he uses Forge, then tell him to go on our [Curse](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice-client) page, then go to files and choose the right version of the mod with [Forge] in the name.

**Comment by ChrisS-code** [comment]
but other mods like litematica and minihud work great with him and he sure uses fabric. do you mean he has to install plasmo voice chat from the fabric site?

**Comment by KPidS** [comment]
It just seems like he doesn't have the mod install, maybe it's the opposite and he installed Forge mod for the Fabric. Ask him to launch the game, then join the server and try to use the mod. After that, close the game, go to `.minecraft/logs` folder and send me `latest.log` file. 

Or use modlist mod and check if Plasmo Voice mod shows up in mod list at all.

**Comment by ChrisS-code** [comment]
Here it is
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6369262/latest.log)

**Comment by KPidS** [comment]
I need to clarify, you can open menu with `V` key and see the icon above your XP when you are using PTT button and your friend can't?

**Comment by ChrisS-code** [comment]
yes

**Comment by howkawgew** [comment]
It looks like the mod is running correctly, does your friend see these buttons in Controls? Are they all white?
![image](https://user-images.githubusercontent.com/73640655/115955275-2f786580-a4fe-11eb-987f-6b84e31aef2e.png)

**Comment by ChrisS-code** [comment]
oh how stupid, it works fine now, he connected 2 keybinds with v.

Thanks for the help!!
