### ISSUE TITLE
Крашает

### ISSUE THREAD

**Issue by playgamesgo** [plasmoapp/plasmo-voice#23]
При запуске мода получаю ошибку 
![image](https://user-images.githubusercontent.com/69041678/115984306-0d8aeb80-a5af-11eb-8d7e-1527befac48c.png)
[crash-2021-04-25_10.08.17-fml.txt](https://github.com/plasmoapp/plasmo-voice/files/6371435/crash-2021-04-25_10.08.17-fml.txt)

**Comment by howkawgew** [comment]
Через какой лаунчер вы запускаете Minecraft?

**Comment by playgamesgo** [comment]
> Через какой лаунчер вы запускаете Minecraft?

GravitLauncher

**Comment by howkawgew** [comment]
Попробуй в своем лаунчере найти параметры запуска Java и вписать туда аргумент -Djna.nosys=true

**Comment by playgamesgo** [comment]
> Попробуй в своем лаунчере найти параметры запуска Java и вписать туда аргумент -Djna.nosys=true

Не помогло

**Comment by howkawgew** [comment]
У тебя же есть файл C:\Users\pplay\AppData\Local\Temp\jna-106877860\jna6526374693419680830.dll?

**Comment by playgamesgo** [comment]
> У вас же есть файл C:\Users\pplay\AppData\Local\Temp\jna-106877860\jna6526374693419680830.dll?

Нету

**Comment by howkawgew** [comment]
**Я не знаю что делать.**

**Comment by lit7355** [comment]
> > Через какой лаунчер вы запускаете Minecraft?
> 
> GravitLauncher
попробуй с другого лаунчера запустить клиент с модом, если все заработает, значит проблема будет крытся в самом GravitLauncher

**Comment by KPidS** [comment]
Check this new update to see if the issue still persists https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.8-fabric-test

**Comment by KPidS** [comment]
We will assume that the issue is fixed now, but feel free to open the issue if you encounter it again.
