### ISSUE TITLE
Error on listening PlayerSpeakEvent

### ISSUE THREAD

**Issue by Karonus** [plasmoapp/plasmo-voice#230]
#228 
When I try listening PlayerSpeakEvent I get this error:
`org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event su.plo.voice.events.PlayerSpeakEvent. Static getHandlerList method required!`

**Comment by Karonus** [comment]
I've fixed **PlayerSpeakEvent** by adding these lines of code
```
public static HandlerList getHandlerList() {
    return HANDLERS_LIST;
}
```

**Comment by Karonus** [comment]
Fix it please

**Comment by apehum** [comment]
Can you test this version?
https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.12-test

**Comment by Karonus** [comment]
> Can you test this version? https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.12-test

Everything works, thank you

**Comment by bottleofench** [comment]
Sorry, I thought this method would be redundant because of an already existing method performing the same function, so I removed it without checking the plugin for errors. I will continue working on API soon.

**Comment by Karonus** [comment]
> Sorry, I thought this method would be redundant because of an already existing method performing the same function, so I removed it without checking the plugin for errors. I will continue working on API soon.

Okay, thanks for your help
