### ISSUE TITLE
use SRV record (instead of ip binding)

### ISSUE THREAD

**Issue by Volkor3-16** [plasmoapp/plasmo-voice#233]
Started writing this issue while I was testing, accidentally pressed enter and it auto-submitted. After further setup this isn't needed. It seems like it does follow SRV records.

**Comment by yoricya** [comment]
Have you built an SRV record? If so, how?)

**Comment by Volkor3-16** [comment]
> Have you built an SRV record? If so, how?)

I'm not too sure how I did it - and I don't have the records saved anymore since I moved to simple voice chat, sorry mate
