### ISSUE TITLE
Mod Loading error

### ISSUE THREAD

**Issue by OrangeSniper** [plasmoapp/plasmo-voice#234]
This happens with both stable and prerelease.
version: 1.19
modloader: Forge
[crash-2022-08-04_13.17.16-fml.txt](https://github.com/plasmoapp/plasmo-voice/files/9261873/crash-2022-08-04_13.17.16-fml.txt)
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/9261875/latest.log)

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
