### ISSUE TITLE
Maven repository authorization failed, status: 403 Forbidden

### ISSUE THREAD

**Issue by bivashy** [plasmoapp/plasmo-voice#238]
There is some error with plasmo voice repository.

It logs: `Could not transfer artifact su.plo.voice:spigot:pom:1.0.11 from/to plasmo-repo (https://repo.plo.su): authorization failed for https://repo.plo.su/su/plo/voice/spigot/1.0.11/spigot-1.0.11.pom, status: 403 Forbidden`

1. I tried to remove .m2 folder.
2. I have internet connection, and i live in Kazakhstan (Maybe this will help with this issue)
3. My pom.xml valid. (Other dependencies does not gives error)
4. I tried to use http instead of https but it also gives error:
`Could not transfer artifact su.plo.voice:spigot:pom:1.0.11 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [plasmo-repo (http://repo.plo.su, default, releases+snapshots)]` 
5. I have access from my browser
![](https://user-images.githubusercontent.com/85439143/184608260-51766f3d-0caf-43bf-8b67-55d604cd4b26.png)
6. I have another repositories in my pom.xml, but i tried to remove them also, and build, but it does not worked

Maybe i should add additional to the pom.xml? Or this is repository issue?
Also i can send my full pom.xml with other repositories and dependencies

RU:
Имеются проблемы с репозиторием plasmovoice при сборке maven

Сама ошибка: `Could not transfer artifact su.plo.voice:spigot:pom:1.0.11 from/to plasmo-repo (https://repo.plo.su): authorization failed for https://repo.plo.su/su/plo/voice/spigot/1.0.11/spigot-1.0.11.pom, status: 403 Forbidden`

1. Я удалял папку .m2
2. У меня есть интернет соединение и я живу в Казахстане (Может это влияет)
3. Мой pom.xml полностью исправен (Другие зависимости без проблем работают)
4. Я пытался использовать http вместо http, была другая ошибка: `Could not transfer artifact su.plo.voice:spigot:pom:1.0.11 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [plasmo-repo (http://repo.plo.su, default, releases+snapshots)]`
5. Я имею доступ к сайту с браузера
![](https://user-images.githubusercontent.com/85439143/184608260-51766f3d-0caf-43bf-8b67-55d604cd4b26.png)
6. I have another repositories in my pom.xml, but i tried to remove them also, and build, but it does not worked

Может я должен что нибудь добавить в pom.xml? Или же это проблема репозитория?
При надобности могу скинуть полный pom.xml с другими зависимостями.

pom.xml:
```
    <repositories>
        <repository>
            <id>plasmo-repo</id>
            <url>https://repo.plo.su</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Plasmo Voice -->
        <dependency>
            <groupId>su.plo.voice</groupId>
            <artifactId>spigot</artifactId>
            <version>1.0.11</version>
            <scope>provided</scope>
        </dependency>
   </dependencies>
```

**Comment by apehum** [comment]
Вероятно проблема в Cloudflare, я добавил repo.plo.su в исключение файрвола, может быть это поможет

**Comment by bivashy** [comment]
> Вероятно проблема в Cloudflare, я добавил repo.plo.su в исключение файрвола, может быть это поможет

Да, всё работает, спасибо огромное!
