### ISSUE TITLE
[error] Crash on loading the world 

### ISSUE THREAD

**Issue by Hugo0272** [plasmoapp/plasmo-voice#242]
[crash-2022-08-25_23.19.07-client-2.txt](https://github.com/plasmoapp/plasmo-voice/files/9430925/crash-2022-08-25_23.19.07-client-2.txt)

Crash when starting the world

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
