### ISSUE TITLE
People who can't speak shouldn't have the speaker icon crossed out above their head

### ISSUE THREAD

**Issue by Jetpack-Cat** [plasmoapp/plasmo-voice#244]
It seems like the only options are for everyone playing who hasn't forwarded the port to see the ugly crossed out speaker icon above other players heads, or to turn it off entirely so you can't see who's speaking in servers that have forwarded the port?

How about an option to show the icon when the port is forwarded and someone is speaking, but to also hide it on servers that haven't forwarded the port. Most people playing won't forward the port, so there's a useless speaker icon above their heads. If I turn it off though then the players on servers who have forwarded the port won't see the speaker icon, right?

**Comment by Toldoven** [comment]
The icon should not be visible if you are playing on a server without Plasmo Voice. 

If you want, you can also make a resource pack that will specifically make the icon you want invisible.
