### ISSUE TITLE
Как сделать что-бы все друг друга слышали из любой точки карты?

### ISSUE THREAD

**Issue by ghost** [plasmoapp/plasmo-voice#245]
Как в дискорде

**Comment by thehaffk** [comment]
Никак

**Comment by ghost** [comment]
А когда нибудь можно будет?

**Comment by DeadFinder** [comment]
Ну по логике можно написать плагин просто и отправлять всем игрокам войс, у меня на основе этого плагин на рации сделан, ивент когда игрок говорит только почему-то не работает, может ответит разработчик плагина и поможет мне, будет неплохо, может напишу маленький плагин на глобальный войс на основе PlasmoVoice если ошибку пофиксят мне.

**Comment by thehaffk** [comment]
> А когда нибудь можно будет?

Да

**Comment by Toldoven** [comment]
https://github.com/plasmoapp/pv-addon-groups
https://github.com/plasmoapp/pv-addon-broadcast
