### ISSUE TITLE
Проблема с плагином

### ISSUE THREAD

**Issue by Lucifer2033** [plasmoapp/plasmo-voice#246]
у меня стоит мод и на сервере стоит плагин  но на сервере пишет что плагин не подключен в консоли 
[08:31:27 INFO]: [PlasmoVoice] Enabling PlasmoVoice v1.0.11
[08:31:27 INFO]: [PlasmoVoice] Voice UDP server started on /0.0.0.0:25767
я через ufw разрешил подключатся к порту udp для всех айпи что не так?
версия ядра сервера git-Purpur-1632 (MC: 1.18.2)*

**Comment by softy-oniguru** [comment]
Поддерживаю, та же проблема. Не могу разобраться и найти причину.
