### ISSUE TITLE
При разговоре отключается плазмо войс

### ISSUE THREAD

**Issue by XoMkaaa** [plasmoapp/plasmo-voice#248]
Разговариваю с типами через это мод и потом он отключается на время. а потом включается. При выключении в настройках мода выводит сообщение "Подключение к UDP серверу". В других голосовых чатах все работает и интернет у меня хороший. У других людей на сервере где происходит такая проблема всё работает без проблем. Использую фабрик на версии 1.16.5. Пробовал без модов только с плазмо войсом проблема не решается.
![2022-07-31_22 15 00](https://user-images.githubusercontent.com/112865604/188432029-6be58123-78c7-4946-81a7-55dc2d38a943.png)

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
