### ISSUE TITLE
Не работает микрофон в Plasmo voice на Fedora Linux.

### ISSUE THREAD

**Issue by PRIMUS8** [plasmoapp/plasmo-voice#251]
Проблема такая. Всё работало прекрасно на Windows 10 но я скопировал папку .minecraft, установил Fedora Linux 36 (Workstation Edition), запустил Майнкрафт и у меня не работает микрофон, но при этом я могу слышать всех игроков. Ещё я заметил что после запуска Майнкрафта и захода на сервер у меня работает индикатор в настройке "Порог активации" (постоянно колебается изза шумов и когда я говорю в микрофон)
![image](https://user-images.githubusercontent.com/90788786/190710376-46b0cf9b-3cab-4977-943c-2c4ac8ad3b25.png)
но после того как я нажимаю Alt этот индикатор зависает на одном месте.
Также иконка микрофона над панелью тоже зависает и не исчезает, но при этом меня никто не слышит.
![image](https://user-images.githubusercontent.com/90788786/190711663-cb77eeb6-0c34-4de3-bdbd-c07676d1aefe.png)
С другими модами из моей сборки никаких проблем не обнаружено.

**Comment by nikes** [comment]
@PRIMUS8 Скорее всего проблема в моде со стороны клиента для взаимодействия с Linux драйверами, ну или в самих драйверах Linux.

**Comment by nasOS-official** [comment]
А у вас pulse audio или alsa?

**Comment by PRIMUS8** [comment]
> А у вас pulse audio или alsa?

Что это, я не шарю) как узнать?
