### ISSUE TITLE
PlasmoVoice не установлен на сервере, хотя он есть

### ISSUE THREAD

**Issue by wleka** [plasmoapp/plasmo-voice#255]
Здрасти, короче я решил поставить plasmovoice 2.0.0 и захожу на сервер, и пишет что на сервере не установлен PlasmoVoice aRofl

https://i.imgur.com/KNo9BNN.png

**Comment by Toldoven** [comment]
На сервере стоит PV 1хх, он не совместим с клиентом 2хх. Нужно чтобы на сервере тоже стоял 2хх
