### ISSUE TITLE
[Feature Request] Golbal voice chat.

### ISSUE THREAD

**Issue by Apricityx** [plasmoapp/plasmo-voice#261]
Please add an option that control if the voice can be heard anywhere including different dimension.
I know this feature already realised by Simple Voice Chat,but it's too difficult to players who do not know how to configure it.
A feature needed by players is that they use mod by just adding a mod into mods folder,and all the configurations are on the server.
I've tried fixing it out,but it doesn't work.

**Comment by Toldoven** [comment]
https://github.com/plasmoapp/pv-addon-groups
