### ISSUE TITLE
Bungee support

### ISSUE THREAD

**Issue by lynrayy** [plasmoapp/plasmo-voice#267]
No instructions for bungee servers. How to use it?

**Comment by StKillReal** [comment]
Just put plasmovoice-server.jar into backend server plugins folder.
U don't need to install the plugin on ur bungee directly

**Comment by lynrayy** [comment]
But it doesn't work like that anyway.
I have bungee+hub server on one machine, and main server on the other. And all this stuff located in one local network with my PC.

**Comment by Toldoven** [comment]
Docs with proper guides on Bungee will be out soon
