### ISSUE TITLE
Do player voices trigger sculk sensors and wardens?

### ISSUE THREAD

**Issue by MagmaSlime123** [plasmoapp/plasmo-voice#269]
Title.

Simple Voice Chat does have an addon that adds this, but its Fabric-only.

This would be amazing to have in this mod/plugin.

No issue template exists, so don't get mad at me for asking a question.

**Comment by thehaffk** [comment]
https://github.com/Apehum/pv-sculk

**Comment by Toldoven** [comment]
https://github.com/plasmoapp/pv-addon-sculk
