### ISSUE TITLE
Проблемы с Wurst

### ISSUE THREAD

**Issue by ZarsQv** [plasmoapp/plasmo-voice#270]
Заходил на сервера без чита Wurst. Недавно решил зайти с ним.
Зашел но PlasmoVoice говорил якобы самого плагина на данном сервере нету. Дело не в сервере - т.к на всех серверах с PlasmoVoice так.

**Comment by crexlight** [comment]
Это тебе надо в Wurstе твоём отключить функцию "VanillaSpoof" которая обманывает сервер, меняя название клиента на Vanilla.
