### ISSUE TITLE
[BUG] Hearing the last few ms of the last transmitted voice

### ISSUE THREAD

**Issue by TheAyes** [plasmoapp/plasmo-voice#272]
So everytime my friends says something and then says something again I can hear the last few milliseconds of their last sentence before their new sentence, which is very weird and confusing especially if it's a short word and you hear that last word at the start of their new sentence.

**Comment by thehaffk** [comment]
Known bug, fixed in 2.X.X

**Comment by Toldoven** [comment]
Fixed in 2xx
