### ISSUE TITLE
player icons for voluntary muting/deafening

### ISSUE THREAD

**Issue by machineonamission** [plasmoapp/plasmo-voice#274]
I think there should be an icon shown above a player when they voluntarily mute/disable VC from the voice settings menu.
When a player mutes themself, the existing muted mic icon should show above the player.
When a player disables their VC entirely, either use the existing "Player is muted" icon or make a new icon similar to Discord's "deafen" icon 
![image](https://user-images.githubusercontent.com/35177464/214997530-79ed9894-135b-4e22-907a-309014624398.png)

**Comment by thehaffk** [comment]
Will be available in 2.X.X 
https://i.imgur.com/tgNng4h.gif
