### ISSUE TITLE
слышу себя когда говорю 

### ISSUE THREAD

**Issue by awentivzera** [plasmoapp/plasmo-voice#277]
слышу себя когда разговариваю, проблема проявилась на пустом месте, не могу понять в чем прикол

**Comment by Toldoven** [comment]
Возможно ты поставил Sound Physics. В нём есть не баг, а фича, что ты слышишь эхо своего голоса. Отключить можно где-то в настройках. Если проблема не в этом, то я хз в чём, нужно больше информации.
