### ISSUE TITLE
Plasmo Voice preventing some clients connecting to server [Fabric]

### ISSUE THREAD

**Issue by glarmer** [plasmoapp/plasmo-voice#278]
Platform: Fabric 1.19.2
Error: java.lang.NoClassDefFoundError: Could not initialize class tomp2p.opuswrapper.Opus
Log: https://mclo.gs/yPMJWow

Description:
Some clients experience this issue when connecting to a server, while other clients are fine. Oddly enough it seems to consistently effect the same people, so some people have this error while others do not, despite having the same Minecraft setup. The resulting effect is that they are disconnected from the server.

**Comment by Toldoven** [comment]
Probably was fixed in 2xx.

We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
