### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by N1kolsky** [plasmoapp/plasmo-voice#28]
На сервере стоит плагин, мод установлен последней версии на фабрик, все равно не работает.
При перезаходе появляется иконка с микрофоном "проблема с подключением", а после и вовсе при нажатии кнопки открыть меню пишет, что плаги PlasmoVoice не установлен на сервере.
PS. вижу неподключенных к моду игроков. Могу менять настройки слышу себя при проверке, но не слышу других игроков.
![image](https://user-images.githubusercontent.com/83508137/116787660-016ec480-aaae-11eb-96f1-f666f90f6e4a.png)
![image](https://user-images.githubusercontent.com/83508137/116787636-ddab7e80-aaad-11eb-9bf8-c0daecd49bdd.png)
![image](https://user-images.githubusercontent.com/83508137/116787614-a5a43b80-aaad-11eb-8c29-b6292c033d94.png)
![image](https://user-images.githubusercontent.com/83508137/116787662-10ee0d80-aaae-11eb-8a60-ab0ba3425c29.png)

**Comment by howkawgew** [comment]
Это ваш сервер? У остальных игроков нет такой проблемы?

**Comment by N1kolsky** [comment]
> Это ваш сервер? У остальных игроков нет такой проблемы?

Нет, не мой, редко у некоторых игроков встречал такую проблему.

**Comment by howkawgew** [comment]
Вероятнее всего проблема на сервере (Например, неправильно указан порт или он вовсе закрыт).

**Comment by N1kolsky** [comment]
> Вероятнее всего проблема на сервере (Например, неправильно указан порт или он вовсе закрыт).

А почему некоторые люди все равно общаются у них всеработает, может все таки проблема на стороне клиента

**Comment by howkawgew** [comment]
Я не думаю что это как-то поможет разобраться в проблеме. Но было бы неплохо если бы вы скинули `latest.log` из папки `/.minecraft/logs`.

**Comment by N1kolsky** [comment]
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6412968/latest.log)

**Comment by Apehum** [comment]
По логам увидел, что это ГП ("Connecting to gpworlds.ru"), это так? Если да, то там нужно заходить по какому-то другому айпи, чтобы работал войсчат

**Comment by N1kolsky** [comment]
> По логам увидел, что это ГП ("Connecting to gpworlds.ru"), это так? Если да, то там нужно заходить по какому-то другому айпи, чтобы работал войсчат

Да это ГП, можете подсказать айпи пожалуйста, потому что я подключаюсь по домену gpworlds.ru

**Comment by Apehum** [comment]
Посмотри в группе вк ГП, там вроде бы был айпи по которому нужно подключаться
