### ISSUE TITLE
[ Suggestion ] Add virtual voice to api.

### ISSUE THREAD

**Issue by Godwhitelight** [plasmoapp/plasmo-voice#281]
I wanted to make a Spigot Plugin that lets me play music thu the voice chat.
I wasnt able to do that because I had no idea how to make a virtual voice without making a fake player and send it thu him.

**Comment by Godwhitelight** [comment]
hello?

**Comment by thehaffk** [comment]
Hello! Thank you for your interest in creating such a plugin for Spigot. We understand the challenge you faced in implementing a virtual voice without making a fake player. 

We have some good news! This feature is being actively developed and will be included in the upcoming Plasmo Voice 2.0.0 release. Once the new version is available, you should be able to easily achieve your desired functionality without having to create a fake player.

Stay tuned for the Plasmo Voice 2.0.0 release, and don't hesitate to ask if you have any questions or need further support.

Our Discord https://discord.gg/qgFdm7rB7H

**Comment by Godwhitelight** [comment]
The discord link is invalid....

**Comment by thehaffk** [comment]
![image](https://user-images.githubusercontent.com/73640655/227716953-822701d3-d92d-4426-8666-ef2cb5df06a8.png)
????

**Comment by Toldoven** [comment]
Example: https://github.com/plasmoapp/pv-addon-discs

Better API docs coming soon
