### ISSUE TITLE
Crash on 1.19.4

### ISSUE THREAD

**Issue by StKillReal** [plasmoapp/plasmo-voice#283]
When I try to connect to 1.19.4 server using the last build of mod I got kicked because of Voice Chat. When try to join without voice mod, all works fine. Now Plasmo Voice is the only one thing why I don't update my server to new version. Is there ETA of 1.19.4 build?

**Comment by Toldoven** [comment]
If the outdated version of the mod was the only problem, then the version of the mod for 1.19.4 is out. Clarify if that is not the only problem.
