### ISSUE TITLE
Crash on startup with plasmo 2.0.0 installed on forge 1.19.2

### ISSUE THREAD

**Issue by manofthemug** [plasmoapp/plasmo-voice#291]
Here is the error received: The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

Exit code is: -1

**Comment by apehum** [comment]
Install https://modrinth.com/mod/kotlin-for-forge
Crash will be fixed in the next patch (8bd5a8e81c0265cad769980e3765ba9cc209af2a)
