### ISSUE TITLE
(2.0.1) Plasmovoice crashes minecraft when starting minecraft without audio output and connect them while playing

### ISSUE THREAD

**Issue by ImGRUI** [plasmoapp/plasmo-voice#294]
Log: https://mclo.gs/TgW70qE
Quilt 0.18.7
QFAPI 6.0.0 beta-3 0.76.0
Minecraft 1.19.4

**Comment by apehum** [comment]
Should be fixed in v2.0.3: https://modrinth.com/plugin/plasmo-voice/version/fabric-1.19.4-2.0.3
