### ISSUE TITLE
Crash on 1.19.2 43.2.8

### ISSUE THREAD

**Issue by LunarDev-git** [plasmoapp/plasmo-voice#296]
It crashes as soon as I start up the server

[crash-2023-04-03_13.48.13-fml.txt](https://github.com/plasmoapp/plasmo-voice/files/11138394/crash-2023-04-03_13.48.13-fml.txt)

**Comment by cswimr** [comment]
Getting the same error as this issue, figured I'd post [my log](https://mclo.gs/SY93BNY) here as well.

It looks like Plasmo Voice is trying to use something client-sided on a dedicated server, see below:

```Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Options for invalid dist DEDICATED_SERVER```
You can find that exception message on line 143 of my log and line 56 of the OP's log.

**Comment by apehum** [comment]
Fixed in v2.0.3: https://modrinth.com/plugin/plasmo-voice/version/forge-1.19.2-2.0.3
