### ISSUE TITLE
Placeholders bug

### ISSUE THREAD

**Issue by NyaomiDEV** [plasmoapp/plasmo-voice#297]
https://github.com/plasmoapp/plasmo-voice/blob/aa1610bdc0712671cf48cea82898ecc7f20bf277/server/paper/src/main/kotlin/su/plo/voice/paper/integration/VoicePlaceholder.kt#L32-L44

How can the camelCase params ever be displayed if you convert them to lowercase before checking?

**Comment by NyaomiDEV** [comment]
https://github.com/plasmoapp/plasmo-voice/blob/b071af783b1acedeeaf7e86d43b20dada4b9205a/api/server-common/src/main/java/su/plo/voice/api/server/player/VoicePlayer.java#L33-L41

https://github.com/plasmoapp/plasmo-voice/blob/b071af783b1acedeeaf7e86d43b20dada4b9205a/server/paper/src/main/kotlin/su/plo/voice/paper/integration/VoicePlaceholder.kt#L39-L41

Another bug I spotted is that those probably are supposed to be function calls.

**Comment by apehum** [comment]
In kotlin, Java methods with prefix `is` or `get` can be accessed as kotlin properties

**Comment by NyaomiDEV** [comment]
> In kotlin, Java methods with prefix `is` or `get` can be accessed as kotlin properties

Oh, I did not know that. I assumed that because, in my testing, both placeholders return `false` even when the user has their mic muted or has voice disabled.

Probably the issue is somewhere else, then.

**Comment by apehum** [comment]
Should be fixed by 788bd5ec10197bf1cf013d8b2f4971a0fc42fd76

**Comment by NyaomiDEV** [comment]
> Should be fixed by [788bd5e](https://github.com/plasmoapp/plasmo-voice/commit/788bd5ec10197bf1cf013d8b2f4971a0fc42fd76)

I offer myself to test it quickly, if you have a jar file to send my way.

**Comment by apehum** [comment]
https://github.com/plasmoapp/plasmo-voice/releases/download/2.0.3/PlasmoVoice-Paper-2.0.3.jar

**Comment by NyaomiDEV** [comment]
> https://github.com/plasmoapp/plasmo-voice/releases/download/2.0.3/PlasmoVoice-Paper-2.0.3.jar

It only updates upon join. Subsequent updates don't come through IF DONE VIA HOTKEYS. Toggling in the Plasmo Config section goes through 99% of the times.

**Comment by apehum** [comment]
> > https://github.com/plasmoapp/plasmo-voice/releases/download/2.0.3/PlasmoVoice-Paper-2.0.3.jar
> 
> It only updates upon join. Subsequent updates don't come through IF DONE VIA HOTKEYS. Toggling in the Plasmo Config section goes through 99% of the times.

Fixed by eb11b40191b97252871f829bbefb3c8293df9c60
