### ISSUE TITLE
The curseforge link is invalid.

### ISSUE THREAD

**Issue by lit7355** [plasmoapp/plasmo-voice#3]
Title says it all.
![Снимок экрана (36)](https://user-images.githubusercontent.com/81138087/114123484-bbeb2b80-9935-11eb-8b4c-12262a94db55.png)
apehum pls fix

**Comment by KPidS** [comment]
CurseForge page is not approved yet. Use [GitHub releases](https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.0) to download the client.
