### ISSUE TITLE
Plasmo voice not working on Serverminer forge server

### ISSUE THREAD

**Issue by OrangeSniper** [plasmoapp/plasmo-voice#304]
here's my log
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/11182057/latest.log)

**Comment by OrangeSniper** [comment]
and my crash file
[crash-2023-04-08_00.22.06-fml.txt](https://github.com/plasmoapp/plasmo-voice/files/11182063/crash-2023-04-08_00.22.06-fml.txt)

**Comment by apehum** [comment]
Update to 2.0.3 (https://modrinth.com/plugin/plasmo-voice/version/forge-1.19.2-2.0.3)

**Comment by OrangeSniper** [comment]
it no longer crashes, however, it still says its not installed
