### ISSUE TITLE
plasmovoice does not work on localhost servers.

### ISSUE THREAD

**Issue by addmix** [plasmoapp/plasmo-voice#306]
Clean installation, 1.18.2 forge version 40.2.0
[client debug.log](https://github.com/plasmoapp/plasmo-voice/files/11205477/debug.log)
[server debug.log](https://github.com/plasmoapp/plasmo-voice/files/11205479/debug.log)

**Comment by thehaffk** [comment]
Hello addmix,

Thank you for reaching out to us regarding your issue. We'd like to inform you that we no longer provide support for the 1.xx versions, including the 1.2.19 that you are currently using. We highly recommend considering a switch to our latest 2.x.x releases for better performance and features.

However, please note that your current Minecraft version 1.18.2 is not yet supported by Plasmo Voice 2.x.x. We are continuously working on updating our support for most Minecraft versions, so keep an eye on our discord for future updates.

If you have any further questions or concerns, please don't hesitate to let us know.
