### ISSUE TITLE
Trouble on a server

### ISSUE THREAD

**Issue by Shagg0** [plasmoapp/plasmo-voice#308]
The mod works in singleplayer, but when I enter to the server I push te "v" and just show me a text saying "Connecting to the UDP server" and nothing more happens, I leaved for 10 minutes or more, and nothing.
![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 19-04-2023 0_25_36](https://user-images.githubusercontent.com/131230880/232968589-fd79792c-53ab-4141-ad3e-01b553319187.png)

**Comment by apehum** [comment]
Read wiki: https://plasmovoice.com/docs/server/installing
