### ISSUE TITLE
Plasmo Voice (plasmovoice) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by RainbowFoxPL** [plasmoapp/plasmo-voice#311]
Idk really what happend. It happens on startup.
[crash-2023-04-19_18.23.20-fml.txt](https://github.com/plasmoapp/plasmo-voice/files/11275566/crash-2023-04-19_18.23.20-fml.txt)

**Comment by apehum** [comment]
Should be fixed in latest versions:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.7
