### ISSUE TITLE
Volume issues

### ISSUE THREAD

**Issue by brokenshadows** [plasmoapp/plasmo-voice#312]
i'm running 2.0.3 on a paper 1.19.4 server. The mod works, but is extremely quiet. Even when setting all the volume sliders up to 200%, it's barely a whisper. Other game sounds are at the proper volumes, but not the voice chat. i'm not sure what i can change to make the entire plugin louder...

**Comment by apehum** [comment]
If the issue persists, try disabling these two options in the advanced tab:
![image](https://github.com/plasmoapp/plasmo-voice/assets/36326454/a1472f4b-82b8-4948-8e46-5e8ae71be3fc)
