### ISSUE TITLE
1.19.4 ViaFabric compatibility.

### ISSUE THREAD

**Issue by xZz404** [plasmoapp/plasmo-voice#314]
### What's the problem?
Best mod for voice-actions, PlasmoVoice, **doesn't support ViaFabric**, as unsupport MultiConnect - connecting with 1.19.4 client to 1.19.3 server = "_Plasmo Voice is not installed on this server_".

### Why not just switch to 1.19.3?
Well, it's simple. Not all **necessary** for me **mods** exist on 1.19.3, which makes this option **unacceptable**.

### So, what is the point of this issue?
**Find a solution** with the help of the community or the developers themselves.

**Comment by xZz404** [comment]
### Some information about the server and system:
**Server**:
1. Core: **Pufferfish 1.19.3**;
2. 100% Installed PlasmoVoice.

**System**:
1. Ryzen 5 5600H, RTX 3050 Ti (**Laptop**, no Max-Q);
2. **Windows 10** 22H2;
3. Minecraft launcher: **MultiMC**;
4. ViaFabric version: 0.4.10+33-dev.

<details><summary>List of mods:</summary>
<p>

- 3dskinlayers;
- alternate-current;
- animatica;
- antighost;
- appleskin;
- BetterF3;
- bettermounthud;
- BoatBreakFix;
- Bookshelf;
- borderless-mining;
- cem;
- chat_heads;
- chunksfadein;
- CITResewn;
- CleanView;
- Clumps;
- connectivity;
- continuity;
- cullleaves;
- deathlog;
- Debugify;
- DimThread;
- dynamic-fps;
- eating-animation;
- emotecraft;
- entity_texture_features;
- entityculling;
- fabricskyboxes;
- fallingleaves;
- Fastload;
- ferritecore;
- highlight;
- Highlighter;
- holdthatchunk;
- Iceberg;
- ImmediatelyFast;
- indium;
- InventoryProfilesNext;
- iris;
- ItemBorders;
- ItemPhysicLite;
- lambdynamiclights;
- language-reload;
- libIPN;
- lithium;
- malilib;
- memoryleakfix;
- mixintrace;
- modelfix;
- modmenu;
- morechathistory;
- moreculling;
- moremcmeta;
- moremobvariants;
- MouseTweaks;
- music_player;
- NoChatReports;
- notenoughanimations;
- notenoughcrashes;
- plasmovoice-fabric;
- portalsgui;
- Prism;
- reeses_sodium_options;
- screenshot-to-clipboard;
- servercore;
- shulkerboxtooltip;
- smoothboot;
- smoothchunk;
- sodium-extra;
- sodium;
- starlight;
- stendhal;
- viafabric;
- WI-Zoom;
- worldedit;
- XaerosWorldMap.

</p>
</details>

**Comment by xZz404** [comment]
Fixed. Cured by time.

**Comment by MagM1go** [comment]
Bump. Trying join with plasmovoice for 1.21.4 on server with 1.21.1 with ViaFabricPlus and getting "Plasmo Voice is not installed on this server"
