### ISSUE TITLE
Simple Voice chat and plasmo voice on the same port

### ISSUE THREAD

**Issue by BlueMooon777** [plasmoapp/plasmo-voice#315]
i want simple voice chat and plasmo voice to work together so my plasmo voice players can talk to my simple voice chat players. any help would be helpfull thanks

**Comment by notqtcris** [comment]
on same udp port??? i don't think that is possible

**Comment by BlueMooon777** [comment]
i tried the udp port thing and it didnt work i just want SVC players to talk to PVC players

**Comment by Toldoven** [comment]
This is not possible. Each mod has its own voice chat protocol and they can't communicate with each other

**Comment by andreypfau** [comment]
> This is not possible. Each mod has its own voice chat protocol and they can't communicate with each other

https://github.com/xgfone/snippet/blob/master/snippet/docs/linux/program/so_reuse.md
