### ISSUE TITLE
Random Disconnect

### ISSUE THREAD

**Issue by cootshk** [plasmoapp/plasmo-voice#318]
Whenever I press `m` (my open minimap key), i get kicked for `java.lang.IllegalStateException: Player is not connected to UDP server`

**Comment by thehaffk** [comment]
I think this is because m is mute key by default
Send latest.log file from ./minecraft/logs via mclo.gs site please

**Comment by cootshk** [comment]
I found the issue, I had PlasmoVoice forwarding to 65535/udp, not 25565/udp (docker container stuff)
