### ISSUE TITLE
Игра крашится в ту же секунду, когда я нажимаю Push-To-Talk (macOS)

### ISSUE THREAD

**Issue by etoshapovalov** [plasmoapp/plasmo-voice#320]
Minecraft: JE 1.19.4 (Fabric)
Java: Oracle 17
OS: macOS High Sierra (10.13)
Plasmo Voice: release 2.0.3

Игра запускается, я захожу на сервер, когда нажимаю кнопку Push-To-Talk - игра вылетает в ту же секунду.
Краш репорт не генерируется, лог просто обрывается на моменте краша.
Код выхода: 6 (0x60000028a690)
На более ранней версии Plasmo работал идеально, всё сломалось при переходе на версию Minecraft 1.19.4 (и на версию Plasmo Voice >2.0 соответственно)

Логи (не обращайте внимание на ошибки CIT Resewn, это норма)
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/11525037/latest.log)
[launcher_log.txt](https://github.com/plasmoapp/plasmo-voice/files/11525040/launcher_log.txt)

**Comment by etoshapovalov** [comment]
Краш-лог из операционки, судя по всему Java Audio Voice Capture вызывает SIGABRT
Почему-то есть упоминание какого-то JNA кэша, который был собран для Mac OS 11, возможно в этом проблема и есть.
```
Crashed Thread:        65  Java: Voice Audio Capture

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Users/USER/Library/Caches/*/jna4613500906702022193.tmp (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
```

[java_2023-05-23-150422_Andreys-iMac-Pro.log](https://github.com/plasmoapp/plasmo-voice/files/11543708/java_2023-05-23-150422_Andreys-iMac-Pro.log)

**Comment by etoshapovalov** [comment]
Причем, что удивительно, что старые версии войса (для MC 1.19.3) работали идеально на этом же сетапе. Подскажите пожалуйста, может быть произошли какие-то ломающее изменения при обновлении до 2.0.0?
Это помогло бы мне попробовать починить проблему самостоятельно

**Comment by etoshapovalov** [comment]
Из того что я уже пробовал:
- Пересобрать Plasmo Voice из исходников
- Пересобрать LWJGL (core и openal модули) из исходников (и подменить их в лаунчере)
- Пробовал запускать на разных версиях Java, на JVM разных производителей (сейчас использую JDK от Azul, который используется и для билда, насколько я понимаю)
- Пробовал пересесть с ванильного лаунчера на Prism Launcher (с использованием системной библиотеки OpenAL, вместо LWJGL'овской)

**Comment by apehum** [comment]
Должно быть пофикшено в пререлизе
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.7

**Comment by etoshapovalov** [comment]
> Должно быть пофикшено в пререлизе https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.7

Краш пропал, однако мод всё еще не забирает микрофон. При выборе любого из доступных девайсов захвата (как физических, так и виртуальных) - отсутствует звук (ничего не слышно при включении мониторинга, отсутствует индикация изменения уровня в настройках мода)

(до версии 2.0 всё работало и мод забирал звук нормально)

**Comment by apehum** [comment]
Какой лаунчер? 

В самом захвате ничего фундаментально не поменялось, поэтому я не особо представляю, как оно могло раньше работать

**Comment by apehum** [comment]
Скинь еще конфиг 1.x войса `config/PlasmoVoice/config.json`

**Comment by etoshapovalov** [comment]
> Какой лаунчер?
> 
> В самом захвате ничего фундаментально не поменялось, поэтому я не особо представляю, как оно могло раньше работать

Лаунчер ванильный/стандартный/лицензионный

**Comment by apehum** [comment]
> > Какой лаунчер?
> > В самом захвате ничего фундаментально не поменялось, поэтому я не особо представляю, как оно могло раньше работать
> 
> Лаунчер ванильный/стандартный/лицензионный

Попробуй с Prism Launcher'a, ванильный лаунчер не умеет запрашивать права на микрофон

**Comment by apehum** [comment]
Хотя не уверен, что в старых версиях мака это влияет, поэтому запрос на конфиг pv 1.x еще актуален

**Comment by etoshapovalov** [comment]
> Хотя не уверен, что в старых версиях мака это влияет, поэтому запрос на конфиг pv 1.x еще актуален

Вроде как на High Sierra еще не придумали всю эту тему с пермишнами на каждый чих
Пробую с призма прямо сейчас

**Comment by etoshapovalov** [comment]
> Попробуй с Prism Launcher'a, ванильный лаунчер не умеет запрашивать права на микрофон

Проблемой был реально ванильный лаунчер
Что интересно, при запуске с "Призмы" пропадают все варианты выбора микрофона (остаётся только CoreAudio Default), но при этом при установке нормального микрофона в настройках системы - всё работает отлично.

Спасибо за фикс! На таких стрёмных сетапах как у меня частенько приходится бороться со всякой подобной дичью)

**Comment by apehum** [comment]
Для ванильного лаунчера могу еще предложить поставить `use_javax_input` на `true` в конфиге `config/plasmovoice/config.toml`, возможно это поможет
