### ISSUE TITLE
[Feature Request] Offsetting player voice icons for client

### ISSUE THREAD

**Issue by JpegIsMe** [plasmoapp/plasmo-voice#323]
Hey! Was just wondering if it would be possible to add functionality in the client config (Doesn't necessarily have to be in the UI config) to give us the ability to **offset the icons by a certain amount of pixels up/down/left/right!** This would be a wonderful quality of life feature and would help servers like us who use Plasmo, but do not use the vanilla player nameplate!
![image](https://github.com/plasmoapp/plasmo-voice/assets/38381978/ee1e3511-253c-4c9f-9066-3ad788774ad6)

**Comment by Toldoven** [comment]
It should offset automatically if you set the names in a certain way. I'm not sure how it works exactly though, and why it works with some mods, while doesn't work with other

**Comment by JpegIsMe** [comment]
The reason why it doesn't work in my situation, is because it's a plugin that handles the nametags instead of vanilla, and it uses armorstands to allow for multi-line nametags.

**Comment by apehum** [comment]
I don't think we will implement this
