### ISSUE TITLE
Constant mic reset

### ISSUE THREAD

**Issue by skirple** [plasmoapp/plasmo-voice#324]
I'll go to set my microphone to the one that I always use for everything, and as soon as I either go to a different page in the settings or I go out of the mod menu, it auto resets to "Not Available." I've tried to update my drivers, I have updated them to the best choice, I've reset my PC, and this issue still happens. Unsure what to do.

**Comment by apehum** [comment]
Send logs

**Comment by apehum** [comment]
stale
