### ISSUE TITLE
🌟 [Feature Request] Add ReplayMod support - (Hear your voice when replaying a recorded session)

### ISSUE THREAD

**Issue by User4716** [plasmoapp/plasmo-voice#326]
So there's a mod for Simple voice chat that adds support for Replaymod 
https://www.curseforge.com/minecraft/mc-mods/replay-voice-chat
And this mod allows you to hear everyone's voice when replaying a recorded session if they have Simple voice chat installed

And there is no mod that adds ReplayMod support for Plasmo voice, so that is why I prefer still Simple voice chat more, just because it has Replaymod support.
But on the other hand, Plasmo Voice has more features and is easier to set up on a server and is better in every way in general, except the ReplayMod support.

**So could there be any way to include support for ReplayMod in Plasmo voice?**
That would be amazing!

> ReplayMod source code: https://github.com/ReplayMod/ReplayMod

**Comment by Toldoven** [comment]
Already a thing https://modrinth.com/mod/pv-addon-replaymod/
