### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by karlovm** [plasmoapp/plasmo-voice#33]
I configured all properly and without proxy it works fine.
But when i try to add my proxy i have time out and "connection problems" icon.

My config.yml: 
`udp:
  ip: my_backend_ip
  port: 25555
  proxy_ip: my_proxy_ip # IP of the proxy server, the IP players will connect to, instead of main IP, when connecting to the voice chat
  proxy_port: 25579 # Port for the proxy
`

My nginx config:

`...
stream {
  server {
    listen 25555 udp; # Port, that you've set in `proxy_port` line in the config
    proxy_pass  my_backend_ip:25579; # IP of the voice chat server and its port
  }
}
`

**Comment by howkawgew** [comment]
You should change ports in nginx config to be other way around. Listen port to `25579` and my_backend_ip port to `25555`.

**Comment by karlovm** [comment]
> You should change ports in nginx config to be the other way around. Listen port to `25579` and my_backend_ip port to `25555`.

No it's not. 
But I try and as expected nothing happens!

**Comment by karlovm** [comment]
я перекомпилировал nginx с модулем stream. Извиняюсь за беспокойство

**Comment by Kanorto** [comment]
> You should change ports in nginx config to be the other way around. Listen port to `25579` and my_backend_ip port to `25555`.

hmm, how is this supposed to work? I just have the same problem but in nginx the module is enabled and working. That is, they are on the same port and, accordingly, cannot work together.

**Comment by Kanorto** [comment]
> я перекомпилировал nginx с модулем stream. Извиняюсь за беспокойство
ты сделал как сказал тот человек? и у тебя работает?
