### ISSUE TITLE
Crash when entering a singleplayer

### ISSUE THREAD

**Issue by OlehYBet** [plasmoapp/plasmo-voice#332]
I have the latest version of Plasmo Voice, more specifically [Fabric 1.20] Plasmo Voice 2.0.4. When I enter a single player game and the loading of the world reaches 100%, my game crashes, and when I enter a multiplayer game, it does not crash. I don't know what to do, so I hope this is just a buggy version of the mod. ![Снимок экрана 2023-06-08 210851](https://github.com/plasmoapp/plasmo-voice/assets/131389059/5b602acf-2d0e-4a6b-955d-2ad495bfd1bb)

**Comment by apehum** [comment]
Download version from github:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.4

I will update modrinth versions later

**Comment by OlehYBet** [comment]
> Download version from github: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.4
> 
> I will update modrinth versions later

It still crashes, but not always.

**Comment by apehum** [comment]
Send logs/crashlogs

**Comment by OlehYBet** [comment]
> Send logs/crashlogs

[2023-06-09-7.log](https://github.com/plasmoapp/plasmo-voice/files/11705950/2023-06-09-7.log)

**Comment by apehum** [comment]
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6
