### ISSUE TITLE
Relocate or JIJ javax.inject on Forge.

### ISSUE THREAD

**Issue by Rubydesic** [plasmoapp/plasmo-voice#334]
On Forge, plasmo-voice shades javax.inject, which will break any other mod which includes javax.inject via forge's JIJ system with a ResolutionException.

Solution: Use "relocate" feature of shadowjar to relocate javax.inject, or use "JIJ" feature of Forge mod loader to include javax.inject rather than shadowjar.

**Comment by apehum** [comment]
2.0.7 forge is now using JIJ for this libs:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.7
