### ISSUE TITLE
Can't hear people after their death

### ISSUE THREAD

**Issue by Graciarz** [plasmoapp/plasmo-voice#336]
Plasmo Voice works normally on my server, but as soon as somebody dies, we can't hear them. When another person die, then people who never died can't hear them, but those who have died can communciate with each other. More deaths don't cause any new issues.
Server has Plasmo Voice 2.0.5, but we are using 2.0.1 
Minecraft Forge 43.2.11

**Comment by Hayaomushi** [comment]
Same problem on Fabric server. 

Plasmo 2.0.5

**Comment by apehum** [comment]
Try prerelease:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.7
