### ISSUE TITLE
Crash on Fabric 1.20

### ISSUE THREAD

**Issue by RHydrix** [plasmoapp/plasmo-voice#337]
Fabric Version: 0.14.21
Plasmo Voice Version: 2.0.5

Game crash when I tried to change the activation_icon_position from in game and when I clicked, it instantly crashed

[crash-2023-06-11_23.11.29-client.txt](https://github.com/plasmoapp/plasmo-voice/files/11717218/crash-2023-06-11_23.11.29-client.txt)

**Comment by apehum** [comment]
Try prerelease:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6

**Comment by apehum** [comment]
Fixed in 2.0.6:
https://modrinth.com/plugin/plasmo-voice/versions
