### ISSUE TITLE
[Bug] Immense stuttering on voices when using voice activation

### ISSUE THREAD

**Issue by trbodev** [plasmoapp/plasmo-voice#34]
Just started using this plugin/mod on my server with some friends and we noticed that there was a lot of stuttering when you start speaking when using voice activation (i will try a supply a audio sample soon)

**Comment by KPidS** [comment]
Don't know what are you talking about, so please provide an audio sample.

**Comment by KPidS** [comment]
I don't think it's an issue with the mod since nobody else encountered a similar problem, and I have no idea how to narrow down its cause or reproduce it. Maybe just try it again, and it will work. If not, you can still open the issue in case there is more info to provide.
