### ISSUE TITLE
ПРЕДЛОЖЕНИЕ: Звонки

### ISSUE THREAD

**Issue by lynrayy** [plasmoapp/plasmo-voice#342]
У вас уже есть простой разговор в мире, есть поддержка кастомных пластинок, как насчёт того, что бы добавить что-то вроде телефонных звонков? Как по мне идея отличная, и работает как замена /msg в виде голосового общения. Так же можно в меню взаимодействий запретить вам звонить, или в настройках самого мода отключить входящие

**Comment by apehum** [comment]
https://modrinth.com/plugin/pv-addon-groups
