### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by rewerze** [plasmoapp/plasmo-voice#346]
When I load a single player world it works fine but when I quiting then load the world back in again it gets crashed. i have no problems with servers, only in singleplayer. I use other mods as well but only this cause the crash (knowing that by that when i pulled out this mod from the mods folder, the problem does not seems to happen)
version: fabric - 1.20.1 (mc) - 2.0.5 (mod); downloaded from modrinth
![image_2023-06-21_220046382](https://github.com/plasmoapp/plasmo-voice/assets/48671619/49a65bcd-9ceb-4db8-8bb4-95a23d451837)

**Comment by apehum** [comment]
Should be fixed in prerelease:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6

**Comment by apehum** [comment]
Fixed in 2.0.6:
https://modrinth.com/plugin/plasmo-voice/versions
