### ISSUE TITLE
PlasmoVoice не установлен на сервер.

### ISSUE THREAD

**Issue by Zeque63** [plasmoapp/plasmo-voice#36]
Захожу я на сервере с PlasmoVoice и не работает. На сервере правильно точно установлен голосовой чат, так как у других игроков работает. Мод тоже установил, может конфликтует, я не знаю уже. Неделю не могу исправить

**Comment by howkawgew** [comment]
А что за сервер? Возможно, название сервера может помочь, так как другие пользователи тоже сталкивались с такой проблемой на определенных серверах.

**Comment by Zeque63** [comment]
> А что за сервер? Возможно, название сервера может помочь, так как другие пользователи тоже сталкивались с такой проблемой на определенных серверах.

Сервер ютубера Пятёрки. Вот вышел новый сервер GPFree..
