### ISSUE TITLE
SRV DNS Record supported in PlasmoVoice?

### ISSUE THREAD

**Issue by yoricya** [plasmoapp/plasmo-voice#367]
I need to set SRV DNS record for forwarding Plasmo Voice Server port. 
Conditionally:
there is an address: mc.example.com, port 3323 is forwarded to the Miencraft service which links to the BungeeCord server, I need to create a second SRV record for Plasmo Voice which will link to the main server (without Bungee) on port 9423.
Is this possible?
The problem is that BungeCord and the main server are located on different machines

**Comment by apehum** [comment]
If I understand you correctly, you can just use host.public for this: https://plasmovoice.com/docs/server/proxy/#proxy-and-server-on-different-nodes

**Comment by apehum** [comment]
Stale
