### ISSUE TITLE
neoprotect support plasmo voice update your docs

### ISSUE THREAD

**Issue by Medved0546** [plasmoapp/plasmo-voice#368]
in the docs:
TCP Shield, Ngrok, or NeoProtect — is the TCP Proxy you use to protect your main server. It only supports the TCP protocol.

Plasmo Voice can't work on the TCP protocol.

And there is no properer "DDoS protection proxy as a service" for the UDP protocol used by Plasmo Voice.

That's why you need to make your own UDP Proxy.

but neoprotect say:

![firefox_NyxcOpgkAR](https://github.com/plasmoapp/plasmo-voice/assets/140727790/95f33927-b9c1-4511-85e7-fb60aca198c3)

![firefox_JUrxb9zm3h](https://github.com/plasmoapp/plasmo-voice/assets/140727790/cc5e9094-f492-4d22-ba80-29f64980bb1b)

**Comment by apehum** [comment]
If NeoProtect adds a page on this topic, I'll mention it in the wiki
