### ISSUE TITLE
infinity hear distance 

### ISSUE THREAD

**Issue by Debug-pro-dev** [plasmoapp/plasmo-voice#369]
Hello everyone! Can I make hear distance in plasmovoice infinite and global voice chat over world?

**Comment by tesseract-two** [comment]
https://github.com/plasmoapp/pv-addon-groups
Would this work?

**Comment by apehum** [comment]
You can use https://modrinth.com/plugin/pv-addon-broadcast or https://modrinth.com/plugin/pv-addon-groups for this.
