### ISSUE TITLE
add option to disable activation when in text chat

### ISSUE THREAD

**Issue by ZekeZDev** [plasmoapp/plasmo-voice#372]
Currently whenever a player is typing if they hit the voice activation key it will active their mic in the example of this being the V key this can happen quite commonly, perhaps and option to disable mic activation when game chat is open.

**Comment by apehum** [comment]
Fixed in [2.1.0](https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0) by 5780027142c57d312ba6f7d45ef891c02f6a0795.

Now by default you can't use Push-To-Talk in chat and sign menus.
There is no option to disable it, but if someone will ask for it, I'll add it.
