### ISSUE TITLE
Добавить поддержку Vanish

### ISSUE THREAD

**Issue by ferrumplay11** [plasmoapp/plasmo-voice#381]
Я заметил проблему, когда игрок заходит в vanish то в в списке в котором можно настроить громкость игроков игрок все равно отображается. А ещё игроков в vanish может слышать другой игрок без vanish

**Comment by envizar** [comment]
Я не смог повторить с 1.20.4 сервером/клиентом, SuperVanish и PlasmoVoice 2.0.7
Точнее в списке я отображался, это баг
Но вот слышать игрока в ванише нельзя никак

**Comment by envizar** [comment]
В 2.1.0 не заметил проблемы

**Comment by apehum** [comment]
Duplicate of #358
