### ISSUE TITLE
[NeoForge 1.20.1] Spamming errors to the server console

### ISSUE THREAD

**Issue by BazZziliuS** [plasmoapp/plasmo-voice#383]
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/13848690/latest.log)

Mohist: 1.20.1-544
Forge: 47.2.17
NeoForge: 47.2.17
Bukkit: 997de31d
CraftBukkit: ddc9a2dad
Spigot: d2eba2c8

**Comment by apehum** [comment]
Fixed in 2.1.0-SNAPSHOT, but it's currently not stable:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT
