### ISSUE TITLE
Can't connect to UDP port.

### ISSUE THREAD

**Issue by Hippocat1** [plasmoapp/plasmo-voice#384]
После захода на сервер работает отлично, но в случае, если я и другой игрок говорим одновременно, то мод прекращает работать и при попытке зайти в настройки выдает бесконечное подключение к UDP. Мод работает отлично у двух моих друзей. Я прочёл вики, и для клиентской части не нашёл ничего. Версия 1.18.2. /vlist показывает, что я подсоединён.

After logging in to the server, it works fine, but if I and another player are talking at the same time, the mod stops working and when trying to enter the settings, it issues an endless UDP connection. The mod works great for two of my friends. I read the wiki, and I didn't find anything for the client side. Version 1.18.2. /vlist shows that I am connected.
[2024-01-08-1.log](https://github.com/plasmoapp/plasmo-voice/files/13861225/2024-01-08-1.log)

**Comment by apehum** [comment]
1.x больше не поддерживается
