### ISSUE TITLE
Minecraft crashing due to Plasmo Voice

### ISSUE THREAD

**Issue by makkacprzak** [plasmoapp/plasmo-voice#386]
I am using plasmo version 2.0.8 for 1.20.2

The game crashes seemingly at random after around a minute of running. It has to be due to Plasmo, because it happens only when this mod is present. The crash doesn't generate a report, but here's the latest.log file:
https://mclo.gs/qp9oFhb

**Comment by apehum** [comment]
I can't really help you with this amount of information.

I can only suggest to try [2.1.0-SNAPSHOT](https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT), which uses different natives, so it may help.
