### ISSUE TITLE
Не запускается сборка с модом

### ISSUE THREAD

**Issue by mrksbgg** [plasmoapp/plasmo-voice#387]
При запуске сборки с модом, выдаёт ошибку отсутствия фабрика (???) Версия 1.20.1, Плазмо 2.0.7
![image](https://github.com/plasmoapp/plasmo-voice/assets/101137197/72e4bc91-6ae6-41c3-befe-e0385ed225b6)

Если вырезать зависимость "fabric": "*" в моде, то даже фабрик вообще не запускается
![image](https://github.com/plasmoapp/plasmo-voice/assets/101137197/ad8f8ad6-dcbb-4cef-a794-77720e36faeb)

(скрины не мои, я пытаюсь помочь игроку)

**Comment by mrksbgg** [comment]
plasmovoice-fabric-1.20.1-2.1.0+3821a2f-SNAPSHOT.jar выдаёт то же самое.

**Comment by mrksbgg** [comment]
plasmovoice-fabric-1.20.1-2.1.0+3821a2f-SNAPSHOT.jar выдаёт то же самое.

**Comment by apehum** [comment]
Поставь Fabric API:
https://modrinth.com/mod/fabric-api/versions
