### ISSUE TITLE
Real 3D audio?

### ISSUE THREAD

**Issue by eDexiam** [plasmoapp/plasmo-voice#39]
I've tested plasmo with a friend of mine however I've quickly noticed that it doesn't seem like the sound is actually 3D (I use headphones so it's very noticable), yes the sound does fade from the distance however it doesn't moves from ear to ear when rotating the camera (player head) in the game. I'm not sure if that's how it's intended to work so I just wanted to make sure. Thanks.

**Comment by KPidS** [comment]
It does, maybe you just didn't notice it. We took the code for audio positioning from Simple Voice Chat, however we are currently working on implementing the Open AL sound engine, the same one used by Minecraft.
