### ISSUE TITLE
Майнкрафт фабрик не запускается с модом PlasmoVoice 

### ISSUE THREAD

**Issue by Sheydyara** [plasmoapp/plasmo-voice#390]
скачал последнюю версию 1.20.4, установил в папку с модами (TLauncher 2.899) но фабрик на этой же версии не запускается и постоянно жалуется на несовместимость мода с версией 
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Plasmo Voice' (plasmovoice) 2.0.7 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
как фиксить

**Comment by fleugle** [comment]
попробуй поставить fabric api и в следуйщий раз в гитхабе пиши на английском. Тут не сидят обычно русскоязычные люди, а значит и помочь ничем не смогут.

**Comment by thehaffk** [comment]
> Тут не сидят обычно русскоязычные люди, а значит и помочь ничем не смогут.

это ты после каких наблюдений пришел к такому заключению?

**Comment by apehum** [comment]
Install fabric api:
https://modrinth.com/mod/fabric-api/versions
