### ISSUE TITLE
Plasmo Voice is not installed on this server

### ISSUE THREAD

**Issue by Zundonza** [plasmoapp/plasmo-voice#395]
Strange that on Fabric 1.165 everything works, but when I go to Forge 1.16.5 an error appears in the header

**Comment by DedMaxim** [comment]
Same thing on 1.20.1 Forge 47.2.20. In the console it says that everything is fine but clients don't get connected until /vrc is executed. So, what I did is installed "Player Events" mod and setup it to execute "/execute as ${player} run vrc" on player join event

**Comment by c1390818629** [comment]
After ensuring that there are no conflicts between Minecraft version 1.20.1 and the plasmo voice mod version, I tested three versions of the mod, making sure that the server and client versions were identical and that the network port forwarding settings were correct. Despite these measures, versions 2.0.7 and 2.0.8 of the mod still displayed the message "Plasmo Voice is not installed on this server." Version 2.0.6, on the other hand, indicated that the UPD port forwarding was not enabled.

**Comment by limelier** [comment]
This issue still occurs on 1.20.1 NeoForge, mod version forge-1.20.1-2.0.10.

**Comment by LKirillK** [comment]
When using the velocity + paper bundle, everything works for clients with fabric. But for clients with forge, it says plasmavoice is not installed.
mod version 2.1.2

**Comment by User4716** [comment]
+1

Same here, but "/vrc" doesn't fix it for me, I have a large modpack though
