### ISSUE TITLE
Support mod

### ISSUE THREAD

**Issue by akva5** [plasmoapp/plasmo-voice#406]
Hello, I am writing through a translator, I hope you will understand me. Could you make PlasmoVoice 2.0 support for 1.16.5 so that it works on 1.16.5 servers. I mean, the new version of the mod works with the old version of the plugin 1.0.11

**Comment by apehum** [comment]
You can use [2.1.0-SNAPSHOT](https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT). This version supports 1.16.5, but it's barely tested

1.x versions are no longer supported, and I will not do something like "support from 1.x on 2.x" and vice-versa
