### ISSUE TITLE
GUI Icon remains visible when GUI is hidden with F1

### ISSUE THREAD

**Issue by ghost** [plasmoapp/plasmo-voice#407]
Steps to reproduce:
- Ensure GUI icon overlay is turned on
- Press F1 to hide GUI
- Icon remains visible in chosen position

Expected:
Icon is hidden alongside the rest of the GUI.

Screenshots demonstrating issue:
![2024-06-19_18 45 51](https://github.com/plasmoapp/plasmo-voice/assets/26670632/dd40b808-ce31-4cd6-824c-2b1c17c61f9c)
![2024-06-19_18 45 53](https://github.com/plasmoapp/plasmo-voice/assets/26670632/d363d14f-fe40-43b7-9c0e-bad341d6cd9e)
Note the icon in the bottom right remaining visible.

**Comment by ghost** [comment]
This applies to all the icons by the way, not just the voice chat disabled icon.

**Comment by apehum** [comment]
Fixed in [2.1.0](https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0)
