### ISSUE TITLE
Add server information in "handshake" packet

### ISSUE THREAD

**Issue by erxson** [plasmoapp/plasmo-voice#408]
Было бы круто, если бы первый пакет, который отправляется по UDP протоколу содержал адрес, по которому было установлено подключение. Тогда у меня была бы возможность написать реверс прокси, которое на одном UDP порту могло бы проксировать войс на два и больше серверов. У тспшилда и неопротекта такая же хуйнюшка, но по тсп.

Типо если в пакете записан адрес bibibo.ru то я проксирую чувачка на bibiboRP, а если rapapa.ua, то на rapapaCraft

**Comment by apehum** [comment]
Из-за этого придется менять протокол и ломать совместимость версий, и я не уверен, стоит ли это того
Есть вариант добавить это не ломая совместимость, но тогда при использовании реверс прокси, придется требовать от клиента определенную версию мода

Думаю сделать второй вариант в 2.1. Я добавлю serverIp и serverPort в [PingPacket](https://github.com/plasmoapp/plasmo-voice/blob/v2.1.x/protocol/src/main/java/su/plo/voice/proto/packets/udp/bothbound/PingPacket.java), как это сделано в [хендшейке Майнкрафта](https://wiki.vg/Protocol#Handshake). Ну и добавлю в конфиге возможность менять минимальную версию мода, поддерживаемую на сервере
Этого будет достаточно?

**Comment by erxson** [comment]
Да. Спасибо!

**Comment by apehum** [comment]
Добавил, пререлиз можно скачать [тут](https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT)
Сделал еще тестовый [UDP reverse proxy на Go](https://github.com/Apehum/pv-reverse-proxy), вроде бы все работает без проблем

**Comment by erxson** [comment]
Дичайше крут!
