### ISSUE TITLE
[Bug] Option to switch from push-to-talk to voice activity is greyed out

### ISSUE THREAD

**Issue by helpimnotdrowning** [plasmoapp/plasmo-voice#41]
Cant switch from push-to-talk to voice activated because the button is greyed out.
![image](https://user-images.githubusercontent.com/35247379/118744827-a6153400-b81a-11eb-86c9-bf189d577d8b.png)

**Comment by emielderckx** [comment]
Then thats is turned off in your server (plugin config)

**Comment by KPidS** [comment]
You don't have permission or disabled it in the server config.
