### ISSUE TITLE
Strange icon

### ISSUE THREAD

**Issue by heheboich** [plasmoapp/plasmo-voice#410]
![GOYY8iZDOno](https://github.com/plasmoapp/plasmo-voice/assets/174415082/9fb1eeda-61fc-46e8-a2f3-f24905b9378f)
This icon shows headphones with a red sign. What does this icon above the player's nickname mean?

**Comment by apehum** [comment]
![image](https://github.com/plasmoapp/plasmo-voice/assets/36326454/cd258f8d-cb21-4976-b9db-16f238d0dbd4)
