### ISSUE TITLE
GET request error 523 repo

### ISSUE THREAD

**Issue by Mr-Node** [plasmoapp/plasmo-voice#416]
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve su.plo.voice.api:server:2.1.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve su.plo.voice.api:server:2.1.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.plasmoverse.com/releases/su/plo/voice/api/server/2.1.0-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://repo.plasmoverse.com/releases/su/plo/voice/api/server/2.1.0-SNAPSHOT/maven-metadata.xml'. Received status code 523 from server:

**Comment by Mr-Node** [comment]
As well as any https://repo.plasmoverse.com/ links give error 523

I also assume that I can add a dependency using the api jar file, but I'm new to this

**Comment by thehaffk** [comment]
should be fixed by now
