### ISSUE TITLE
Игрок не может говорить в чат

### ISSUE THREAD

**Issue by ORAMBOas** [plasmoapp/plasmo-voice#42]
У 99% игроков все работает хорошо, но у одного то работает, то нет. В консоле выбивает ник и пишет UDP timed out.
В чём может быть проблема? 
![image](https://user-images.githubusercontent.com/70290058/119025676-063bdf80-b9ad-11eb-969b-6e18c996a27e.png)
У игрока пишет, что на сервере неустановлен плагин.
Вот логи игрока: 
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6517891/latest.log)

**Comment by howkawgew** [comment]
Ну он лох видимо
