### ISSUE TITLE
Game crashes when closing game

### ISSUE THREAD

**Issue by ClassyCustom** [plasmoapp/plasmo-voice#420]
[latest.log](https://github.com/user-attachments/files/17258631/latest.log)
the game will crash on close here is the log file what can I do to fix this?

**Comment by apehum** [comment]
Fixed by 3993993a2573291d3903ae6426578cede7c9f639.
You can download the latest build with fix here: 
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.1-SNAPSHOT
