### ISSUE TITLE
Load on the game and processor

### ISSUE THREAD

**Issue by akva5** [plasmoapp/plasmo-voice#421]
When using the new version 2.1.0 or 2.1.1 on the server, the game is loaded by 70-90% and the processor is 100%. This problem depends on the number of players, for example, if there are a lot of people on spawn during the day and they will all play with plasmovoice, then the load goes on, FPS decreases, this is for many players
![photo_2024-10-09_10-02-34](https://github.com/user-attachments/assets/5457a08d-b7a5-4a45-ab5c-c4e5f2b3e8e1)

**Comment by apehum** [comment]
Try with a new build of 2.1.1: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.1-SNAPSHOT

**Comment by akva5** [comment]
The problem is solved
