### ISSUE TITLE
PlasmoVoice server can not see my client.

### ISSUE THREAD

**Issue by coyneryt** [plasmoapp/plasmo-voice#43]
Plugin version 1.0.1 is not visible to my client, a "No mod" icon appears above my head. Mod version 1.0.1. I tried to put on version 1.0.6. (sorry for my english)

**Comment by howkawgew** [comment]
So. (just note, i think you are likely from  russia so you can use russian language in your issue)

Can you specify more details in issue? is this your server? does the mod work fine for other players?

**Comment by coyneryt** [comment]
Хорошо, спасибо. Это мой сервер. Я пробовал заходить с разных аккаунтов на сервер и был значок обозначающий "Нету мода". Версия 1.16.5 Paper. Есть еще одна особенность, когда я включаю микрофон я могу говорить только секунд 5, потом появляется значок над инвентарем "Микрофон отлючен".

**Comment by KPidS** [comment]
https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server

В этом гайде написаны все возможные проблемы при установке плагина на сервер. Пожалуйста, ознакомься с ним. Если он не помогает, значит ты либо делаешь что-то не так, либо закрыты UDP порты, поэтому в такой ситуации лучше обратится к поддержке хостинга и просить помощи у них.
