### ISSUE TITLE
[Feature] Use Dynamic Surroundings for echo and more

### ISSUE THREAD

**Issue by eDexiam** [plasmoapp/plasmo-voice#44]
Here's a suggestion, integrate dynamic surroundings to make the voice chat work with the echo effect the mod produces when being in big caves.

**Comment by KPidS** [comment]
Added compatibility with Sound Physics mod in the last update.

We are planning to add compatibility with Dynamic Surroundings too, but it's not out for 1.17 yet. Sound Physics is pretty similar though.

**Comment by mateo-m** [comment]
Hey @KPidS,

Just wanted to let you guys know that the original version of Dynamic Surroundings has been hard-forked into two remastered/updated versions, one for Fabric and one for Forge.

Fabric :
- Curseforge : [https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-remastered-fabric-edition](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-remastered-fabric-edition)
- GitHub repository : [https://github.com/maksim789456/DynamicSurroundingsFabric](https://github.com/maksim789456/DynamicSurroundingsFabric)

Forge :
- Curseforge : [https://www.curseforge.com/minecraft/mc-mods/dynamic-surrounding-resurrected](https://www.curseforge.com/minecraft/mc-mods/dynamic-surrounding-resurrected)
- GitHub repository : [https://github.com/Nyfaria/DynamicSurroundingsResurrected](https://github.com/Nyfaria/DynamicSurroundingsResurrected)

Are you still planning on adding compatibility with Dynamic Surroundings to Plasmo Voice ?
