### ISSUE TITLE
don't work on Mac?

### ISSUE THREAD

**Issue by redred1010** [plasmoapp/plasmo-voice#55]
Me and my friend have been trying for ages to get it to work on our computers but it just doesn't seem to be working. It works on my windows just fine.

**Comment by Dan34523** [comment]
Seconded, have had 2 cases of Plasmo not working on Mac Clients. Minecraft crashes when trying to open and generates the following crash report.
[crash-2021-06-21_07.18.37-client.txt](https://github.com/plasmoapp/plasmo-voice/files/6687595/crash-2021-06-21_07.18.37-client.txt)

**Comment by KPidS** [comment]
Check this new update to see if the issue still persists

**Comment by redred1010** [comment]
heyyyy, so I am able to actually launch the game now, and use the menu, but I can't talk to others. I can hear them, but I can't seem to get it to pick up my audio. Its only for Macs.

**Comment by KPidS** [comment]
> heyyyy, so I am able to actually launch the game now, and use the menu, but I can't talk to others. I can hear them, but I can't seem to get it to pick up my audio. Its only for Macs.

It's an issue with macOS not asking for permission to use a microphone. Check this issue on Simple Voice Chat Github, you might find the solution there: https://github.com/henkelmax/simple-voice-chat/issues/24
