### ISSUE TITLE
I have the mod on client 1.17 and the server plugin Paper 1.17, it doesnt work.

### ISSUE THREAD

**Issue by GJungle1** [plasmoapp/plasmo-voice#56]
It shows on /plugins and the commands work, but nothing works, when I press the Settings button says "Plasmo Voice is not installed on this server" but it clearly is. Please help

**Comment by KPidS** [comment]
Please read this guide: 
https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server
