### ISSUE TITLE
[QUESTION] What does fade divisor exactly do?

### ISSUE THREAD

**Issue by StarsDown64** [plasmoapp/plasmo-voice#62]
I'm just not quite sure. I know it divides voice distance to make fade distance, but what is fade distance? The distance at which fade starts? The intervals at which fade increases? Something else entirely? It doesn't seem clear to me.

**Comment by KPidS** [comment]
It's the distance at which fading starts. Before fade distance, the volume is at 100%.

**Comment by StarsDown64** [comment]
Could add that explanation in a comment in the config.
