### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Slypy06** [plasmoapp/plasmo-voice#63]
Plasmo voice server doesn't work with hybrid minecraft server who suport spigot plugin and forge mod like magma or mohist in 1.16.5. The client say "Plasmo Voice is not installed on this server". There is the line who say "Plasmo voice server started on port : xxx" in the logs. I test with the same configuration the plugin on a server with spigot and on a server with mohist and it only work with spigot. There is no error in the logs.

**Comment by KPidS** [comment]
> Thats because magma and mohist are pure trash dont use them. Use spongeforge or don't use anything. Hybrids have always been something stupid.

Basically, yes. We didn't even try to figure out why it doesn't work on Mohist or Magma, and we don't plan to. That's not the use scenario we are aiming for. If you run a Forge server, then you should just use Simple Voice Chat.
