### ISSUE TITLE
Impossibility to talk

### ISSUE THREAD

**Issue by MrEminStar** [plasmoapp/plasmo-voice#64]
Hello! When I press the hotkey to start talking, my microphone may simply not work, and when I go into the PlasmaVoice settings it says: "Plasma Voice is not installed on this server." I have already tried everything, but I could not find a solution. Do you know what the problem is?

Minecraft version - 1.16.5
Installed mod on Fabric
PlasmaVoice mod version - 1.0.6

I have no conflicting mods.
I myself can speak, but in almost all cases my microphone is interrupted and I have to wait 5-15 seconds until it turns on again.
This happens with any microphones that I connect.

**Comment by KPidS** [comment]
Please read the server installation guide, you didn't configure the plugin properly: https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server
