### ISSUE TITLE
[Suggestion] Ability to change the volume of players individually

### ISSUE THREAD

**Issue by CrypiYT** [plasmoapp/plasmo-voice#65]
Hii,
would it be possible to add a feature like in simple voice chat where you can change the volume of players individually? As on some players are pretty loud while others are pretty silent and you can only change the volume globally. Would it be possible to introduce that feature?

**Comment by KPidS** [comment]
https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.10-fabric
