### ISSUE TITLE
NOT VERSION 1.0.9 FOR SPIGOT

### ISSUE THREAD

**Issue by LuckyPolak138** [plasmoapp/plasmo-voice#66]
downloaded mod version 1.0.9, and for spigot where 1.0.9, there is only 1.0.5. I can't speak (does not work). Writes that there is no server when everything is correct.
HELP!

**Comment by KPidS** [comment]
Every version of the server is compatible with every version of the client. 1.0.5 is the last version of the server and 1.0.9 is the last version of the client, and they are compatible. If it doesn't work, then you didn't set up it correctly. Please read this guide: https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server
