### ISSUE TITLE
Mac issue - I get "MultiMc would like access to the microphone" all the time

### ISSUE THREAD

**Issue by spiderkitten** [plasmoapp/plasmo-voice#68]
Hi, I am using Plasmo on a minecraft server I play on that has it enabled, via MultiMC on a Mac (Mojave 10.14.6). It works great, I can hear people and they can hear me, _except_ that:

- if I have it set to "push to talk" every time I press the key to talk my Mac pops up a dialogue box that says "MultiMc would like access to the microphone" which of course, I click OK, and then I press the Push To Talk Button, and it pops up again. 

So I switched to Voice Detection. 

- However, with Voice Detection, it still pops up the message every time I unmute using the unmute key. I am fortunate in that my microphone has a mute button I can use instead, but it's still not my preferred option. I would rather use a key on my keyboard.

In my privacy settings for microphone access, I have MultiMC set as having permission to access the microphone, so I don't know why it has to keep asking me. 

Additionally, there is sometimes a delay in the dialogue box popping up. Not by a lot, just enough for me to think its not going to and then it does.  

<img width="450" alt="dialogue box" src="https://user-images.githubusercontent.com/13283343/125701201-959dc466-9686-4e3c-87e0-5a6ff6e7650c.png">

<img width="450" alt="privacy settings" src="https://user-images.githubusercontent.com/13283343/125701223-fa12307e-9fa2-4dc1-b3e4-9881582e5e4f.png">

Is there a way to fix this?

Minecraft version: 1.17.1
Fabric version:  0.11.6 (fabric api 0.37)
Mod version: 1.0.9
macOS version: Mojave 10.14.6

**Comment by Zanctarian** [comment]
> Hi, I am using Plasmo on a minecraft server I play on that has it enabled, via MultiMC on a Mac (Mojave 10.14.6). It works great, I can hear people and they can hear me, _except_ that:
> 
> * if I have it set to "push to talk" every time I press the key to talk my Mac pops up a dialogue box that says "MultiMc would like access to the microphone" which of course, I click OK, and then I press the Push To Talk Button, and it pops up again.
> 
> So I switched to Voice Detection.
> 
> * However, with Voice Detection, it still pops up the message every time I unmute using the unmute key. I am fortunate in that my microphone has a mute button I can use instead, but it's still not my preferred option. I would rather use a key on my keyboard.
> 
> In my privacy settings for microphone access, I have MultiMC set as having permission to access the microphone, so I don't know why it has to keep asking me.
> 
> Additionally, there is sometimes a delay in the dialogue box popping up. Not by a lot, just enough for me to think its not going to and then it does.
> 
> <img alt="dialogue box" width="450" src="https://user-images.githubusercontent.com/13283343/125701201-959dc466-9686-4e3c-87e0-5a6ff6e7650c.png">
> 
> <img alt="privacy settings" width="450" src="https://user-images.githubusercontent.com/13283343/125701223-fa12307e-9fa2-4dc1-b3e4-9881582e5e4f.png">
> 
> Is there a way to fix this?
> 
> Minecraft version: 1.17.1
> Fabric version: 0.11.6 (fabric api 0.37)
> Mod version: 1.0.9
> macOS version: Mojave 10.14.6

This appears to be a problem with how mute is handled. The correct way is to use a control, but the fabric code appears to just disconnect the mic all-together. This problem can most likely be fixed by using controls instead of disconnecting the mic. I'll open a PR to change how mute is handled, which should fix your issue so it'll only ask for mic when the mic service starts, opposed from spamming the dialogue.

As for how to make it stop asking, that's most likely an issue with Mac.

**Comment by spiderkitten** [comment]
Just an update on this: I am wondering if this was actually a MultiMC issue. I was experiencing an unrelated issue (multimc would freeze my computer when I launched the app) and reinstalling MultiMC didn't help until I installed the development version instead. And since doing that, this Microphone access issue has gone away. It doesn't ask me anymore.

**Comment by KPidS** [comment]
It's likely that this is not the issue with the mod, and I don't think we can do anything about it.
