### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by LuckyPolak138** [plasmoapp/plasmo-voice#69]
[08:16:47] [Thread-139/INFO]: [PlasmoVoice] Voice UDP server started on /0.0.0.0:60600
The server says that everything is working, but on the client it says that Plasmo is not enabled on the server.

**Comment by World4567** [comment]
I tried everything, but there is no effect.

**Comment by kyrtion** [comment]
> 
> 
> [08:16:47] [Thread-139/INFO]: [PlasmoVoice] Voice UDP server started on /0.0.0.0:60600
> The server says that everything is working, but on the client it says that Plasmo is not enabled on the server.

this mod only for Plasmo servers

**Comment by Zanctarian** [comment]
> > [08:16:47] [Thread-139/INFO]: [PlasmoVoice] Voice UDP server started on /0.0.0.0:60600
> > The server says that everything is working, but on the client it says that Plasmo is not enabled on the server.
> 
> this mod only for Plasmo servers

They're trying to make it function on their server.


> [08:16:47] [Thread-139/INFO]: [PlasmoVoice] Voice UDP server started on /0.0.0.0:60600
> The server says that everything is working, but on the client it says that Plasmo is not enabled on the server.

Make sure to check your firewall if possible. Some hosting services automatically block ports that are unused for security purposes. If you use a hosting service, the best action to take is to open a ticket and ask if it would be possible to access port 60600.. you may have to pay a fee, though. The easiest way to get around that is just to own something like a dedicated server, but those definitely aren't available for everyone. Although let me know if you were using the server on your computer, as the story is different in home-hosted environments.

The plugin seems to be working fine, on the bright side.

**Comment by KPidS** [comment]
Sorry for the late reply, but it's likely that you just haven't installed it properly. Please read this guide: https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server
