### ISSUE TITLE
Minecraft crashing due to Plasmo voice client

### ISSUE THREAD

**Issue by Littlebrink** [plasmoapp/plasmo-voice#71]
I have tried starting minecraft multiple times with the voice mod. at first I had some other mods in there but then it crashed so I took those out to see if its the plasmo mods problem and it is. I asked someone who knows a lot about this stuff to help me and they said it has something to do with the plasmo mod. I am on a mac so maybe that's part of the problem. I will leave a log file of when the game crashed below. I would appreciate it if someone looked at it. thank you :D
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6873927/latest.log)

**Comment by Zanctarian** [comment]
> I have tried starting minecraft multiple times with the voice mod. at first I had some other mods in there but then it crashed so I took those out to see if its the plasmo mods problem and it is. I asked someone who knows a lot about this stuff to help me and they said it has something to do with the plasmo mod. I am on a mac so maybe that's part of the problem. I will leave a log file of when the game crashed below. I would appreciate it if someone looked at it. thank you :D
> [latest.log](https://github.com/plasmoapp/plasmo-voice/files/6873927/latest.log)

It's almost definite the issue does not stem from Plasmo as no objective C libraries are used. However, this issue has known to be a bug with Minecraft. In the game's folder ".minecraft" (Note: Could be at a custom location if you use a modpack client like CurseForge).. you need to install the "java-objc-bridge" library as you can't run OSX Minecraft without it.

To install the libraries, go to:
https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar

then put that jar in:
`.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0`

Note: You may need to create folders as needed.

Source: https://bugs.mojang.com/browse/MC-118506
