### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Rezanans-wow** [plasmoapp/plasmo-voice#79]
следовал инструкциям все-равно пишет https://media.discordapp.net/attachments/799651837384065034/875418555900907520/unknown.png

Никак

**Comment by KPidS** [comment]
Прочитай гайд: https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server

Он установлен, но не настроен. Если плагин стоит, но меню мода не работает, это значит что клиент не может подключится к серверу, потому что сервер не настроен. Или у тебя не открыт UDP порт, или у тебя есть какая-то проблема, которая уже описана в гайде. 

Других проблем быть не может, и больше мы тебе ничем помочь не можем.

**Comment by Rezanans-wow** [comment]
порты открыты, все по гайду делалось. Очень жаль, что не смогу воспользоваться 
подобные плагины работали хорошо

**Comment by SkyWatcher2019** [comment]
Если ты используешь BungeeCord, то у сервера с Plasmo Voice должен быть тот же айпи, что и у BungeeCord
