### ISSUE TITLE
It seems that he cannot be used with vivecraft 1.16.5

### ISSUE THREAD

**Issue by Chinglem** [plasmoapp/plasmo-voice#83]
[crash-2021-08-21_22.10.27-client.txt](https://github.com/plasmoapp/plasmo-voice/files/7027394/crash-2021-08-21_22.10.27-client.txt)

There is an incompatible JNA native library installed on this system

**Comment by KPidS** [comment]
We don't support 1.16 anymore, check if there is the same issue on 1.17, and if there is, we will fix it.
