### ISSUE TITLE
GUI Feedback, permission node voice.speak false

### ISSUE THREAD

**Issue by heathfx** [plasmoapp/plasmo-voice#85]
## Expected Behavior
* When the permission node "voice.speak" is set to "false", the microphone icon in the player's GUI should show muted. Making it consistent with how the icon is displayed when a player is muted with /vmute
* When the permission node "voice.speak" is changed to "false" while a player is logged in. Their microphone icon should update (within 5 seconds of the server-side change being made) to indicate they are muted.

## Actual Behavior
* When the permission node "voice.speak" is set to "false", the microphone icon indicates that audio is being transmitted, even though the server is silently ignoring their voice packets.

## Reason this is undesirable
* Confuses the player who is un-aware that they lack the permission to speak.
* Confuses the admin who may not realize the permission node is negated.
* Makes it harder to integrate in a server that uses permission groups to enforce mutes.

**Comment by KPidS** [comment]
Fixing that requires remaking the protocol, and we are going to do that, eventually, but it will take a while since we are planning to do a major update updating the protocol.

**Comment by Toldoven** [comment]
Fixed in 2xx
