### ISSUE TITLE
Mod says it's not installed on server even though server says it is

### ISSUE THREAD

**Issue by martinm07** [plasmoapp/plasmo-voice#87]
I've been trying to get PlasmoVoice to work on [Minehut](https://minehut.com/). I've installed the mod client-side with Fabric, and I've put the plugin JAR into my server.
When I start my server, it says (in the console):
```
[PlasmoVoice] Voice UDP server started on /0.0.0.0:60606
```
However, when I join the server and try use the mod, it says "`Plasmo Voice is not installed on this server`"...
The [How to install Server wiki](https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server) says that if I get the "Voice UDP server started" message, that everything is working fine...

Any ideas on what could be the cause of this?
Difference in versions? Client not seeing the port? I have no idea (I'm just regurgitating random words)...
Thanks for any help

**Comment by emielderckx** [comment]
You need to change the port in the server config to the port minehut gave you. I find it unlikely that they gave you 60606

**Comment by martinm07** [comment]
> You need to change the port in the server config to the port minehut gave you. I find it unlikely that they gave you 60606

I've actually already tried that.
Looking at `server.properties`, I found `server_port=25575` and `query.port=25565`. I tried both of them in the `config.yml`, but no luck...

**Comment by emielderckx** [comment]
It needs to be a different port than the main one your server uses. Contact minehut for that, I don't think they will have that because they are some kind of free hosting. Which is overall bad

**Comment by martinm07** [comment]
Oh really? I didn't realize...
Yeah, I don't think I'll be getting a _different_ open port on Minehut.
But, that sounds like the answer to me. Well, thanks for the help.
