### ISSUE TITLE
Mac not workin :/

### ISSUE THREAD

**Issue by TinyTV1** [plasmoapp/plasmo-voice#89]
so I select my microphone the output works cause I hear my friends, they see my mic icon but they don't hear me, is it cuz I'm on mac, it was working a minute ago so please help

**Comment by KPidS** [comment]
Read this thread: https://github.com/henkelmax/simple-voice-chat/issues/24

It's basically a Mac problem, and I don't think it's fixable from our side. But there are a lot of information and things you might try.
