### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by GxXux** [plasmoapp/plasmo-voice#91]
Hi, I'm using plasmo vc on 1.16.5 server with viaversion on it and on 1.17.1 fabric client. When I firstly join server everything is fine and voice chat works normal, but when I rejoin it keeps kicking me with the following message: "Badly compressed packet- size of 2 is below server threshold of 256" If I delete plasmo vc config from server files and restart the server it again allows me to join but while I disconnect everything occurs same.

**Comment by joex92** [comment]
How was this issue solved? at least share it... or is it because it can't/won't be solved?
