### ISSUE TITLE
Client can't detect all audio sources.

### ISSUE THREAD

**Issue by SSUPII** [plasmoapp/plasmo-voice#93]
Debian GNU/Linux bookworm/sid x86_64

Two input devices are available on the system, the Pulseaudio monitor and audio loopback, and an internal laptop microphone (Seen by any program as Analog Microphone). Under the Audio settings of this mod only "default" is listed with no indication of what default is. Microphone testing shows that "default" is indeed the Pulseaudio monitor as it loops back all PC audio. A second audio source should be listed but isn't.

"arecord -l" output 
```
**** List of CAPTURE Hardware Devices ****
card 1: PCH [HDA Intel PCH], device 0: Generic Analog [Generic Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

**Comment by KPidS** [comment]
It's likely an issue with Java, and I don't think that we can do anything with that. Can you just switch the default device? I'm not sure how it works on Linux.
