### ISSUE TITLE
[Feature] Hide icon under player name through wall

### ISSUE THREAD

**Issue by sya-ri** [plasmoapp/plasmo-voice#96]
If you hide the player's name, only the icon will be visible through the wall.

Would you please make the following changes?
- Add the server setting that can switch the display of the icon through the wall.
- Switch the icon display depending on nametagVisibility

**Comment by KPidS** [comment]
It doesn't make sense to make this optional on the server-side, because it will be easily bypassable. Icons are client-side. And you can enable or disable icons on the client: https://imgur.com/4dMchNs

**Comment by sya-ri** [comment]
Is it possible to force the setting? For example, it is unrealistic to have everyone set when playing a mini game like hide-and-seek.

**Comment by sya-ri** [comment]
@KPidS

I know it can be set on the client, but I forgot to write it.

Is it possible to force the setting? For example, it is unrealistic to have everyone set when playing a mini game like hide-and-seek.
