### ISSUE TITLE
Does not work BungeeCord. Am I doing something wrong?

### ISSUE THREAD

**Issue by Tapeline** [plasmoapp/plasmo-voice#99]
So, I have 1 spigot server and 1 bungee (bot filter)
I have installed plasmovoice on spigot. Wiki says, that if you want to use plasmovoice with bungee, you should install it on every backend server. However, the mod says that I haven't installed plugin. Am I missing something?

**Comment by Toldoven** [comment]
You should install it on the Spigot server. If you did, and it shows in the plugin list, then it's probably not configured properly, and you should try to bind the IP address and check if the port is open. 

Also, it's better to ask for help in the Discord server: https://discord.gg/PGvQSBH9
